// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/LoneWolfPR/MedMarket/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// FirstName applies equality check predicate on the "first_name" field. It's identical to FirstNameEQ.
func FirstName(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldFirstName, v))
}

// LastName applies equality check predicate on the "last_name" field. It's identical to LastNameEQ.
func LastName(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastName, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPhone, v))
}

// AddressStreet1 applies equality check predicate on the "address_street1" field. It's identical to AddressStreet1EQ.
func AddressStreet1(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAddressStreet1, v))
}

// AddressStreet2 applies equality check predicate on the "address_street2" field. It's identical to AddressStreet2EQ.
func AddressStreet2(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAddressStreet2, v))
}

// AddressCity applies equality check predicate on the "address_city" field. It's identical to AddressCityEQ.
func AddressCity(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAddressCity, v))
}

// AddressState applies equality check predicate on the "address_state" field. It's identical to AddressStateEQ.
func AddressState(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAddressState, v))
}

// AddressZip applies equality check predicate on the "address_zip" field. It's identical to AddressZipEQ.
func AddressZip(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAddressZip, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPasswordHash, v))
}

// FirstNameEQ applies the EQ predicate on the "first_name" field.
func FirstNameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldFirstName, v))
}

// FirstNameNEQ applies the NEQ predicate on the "first_name" field.
func FirstNameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldFirstName, v))
}

// FirstNameIn applies the In predicate on the "first_name" field.
func FirstNameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldFirstName, vs...))
}

// FirstNameNotIn applies the NotIn predicate on the "first_name" field.
func FirstNameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldFirstName, vs...))
}

// FirstNameGT applies the GT predicate on the "first_name" field.
func FirstNameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldFirstName, v))
}

// FirstNameGTE applies the GTE predicate on the "first_name" field.
func FirstNameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldFirstName, v))
}

// FirstNameLT applies the LT predicate on the "first_name" field.
func FirstNameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldFirstName, v))
}

// FirstNameLTE applies the LTE predicate on the "first_name" field.
func FirstNameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldFirstName, v))
}

// FirstNameContains applies the Contains predicate on the "first_name" field.
func FirstNameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldFirstName, v))
}

// FirstNameHasPrefix applies the HasPrefix predicate on the "first_name" field.
func FirstNameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldFirstName, v))
}

// FirstNameHasSuffix applies the HasSuffix predicate on the "first_name" field.
func FirstNameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldFirstName, v))
}

// FirstNameEqualFold applies the EqualFold predicate on the "first_name" field.
func FirstNameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldFirstName, v))
}

// FirstNameContainsFold applies the ContainsFold predicate on the "first_name" field.
func FirstNameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldFirstName, v))
}

// LastNameEQ applies the EQ predicate on the "last_name" field.
func LastNameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastName, v))
}

// LastNameNEQ applies the NEQ predicate on the "last_name" field.
func LastNameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLastName, v))
}

// LastNameIn applies the In predicate on the "last_name" field.
func LastNameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldLastName, vs...))
}

// LastNameNotIn applies the NotIn predicate on the "last_name" field.
func LastNameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLastName, vs...))
}

// LastNameGT applies the GT predicate on the "last_name" field.
func LastNameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldLastName, v))
}

// LastNameGTE applies the GTE predicate on the "last_name" field.
func LastNameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLastName, v))
}

// LastNameLT applies the LT predicate on the "last_name" field.
func LastNameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldLastName, v))
}

// LastNameLTE applies the LTE predicate on the "last_name" field.
func LastNameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLastName, v))
}

// LastNameContains applies the Contains predicate on the "last_name" field.
func LastNameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldLastName, v))
}

// LastNameHasPrefix applies the HasPrefix predicate on the "last_name" field.
func LastNameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldLastName, v))
}

// LastNameHasSuffix applies the HasSuffix predicate on the "last_name" field.
func LastNameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldLastName, v))
}

// LastNameEqualFold applies the EqualFold predicate on the "last_name" field.
func LastNameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldLastName, v))
}

// LastNameContainsFold applies the ContainsFold predicate on the "last_name" field.
func LastNameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldLastName, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPhone, v))
}

// AddressStreet1EQ applies the EQ predicate on the "address_street1" field.
func AddressStreet1EQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAddressStreet1, v))
}

// AddressStreet1NEQ applies the NEQ predicate on the "address_street1" field.
func AddressStreet1NEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAddressStreet1, v))
}

// AddressStreet1In applies the In predicate on the "address_street1" field.
func AddressStreet1In(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAddressStreet1, vs...))
}

// AddressStreet1NotIn applies the NotIn predicate on the "address_street1" field.
func AddressStreet1NotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAddressStreet1, vs...))
}

// AddressStreet1GT applies the GT predicate on the "address_street1" field.
func AddressStreet1GT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAddressStreet1, v))
}

// AddressStreet1GTE applies the GTE predicate on the "address_street1" field.
func AddressStreet1GTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAddressStreet1, v))
}

// AddressStreet1LT applies the LT predicate on the "address_street1" field.
func AddressStreet1LT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAddressStreet1, v))
}

// AddressStreet1LTE applies the LTE predicate on the "address_street1" field.
func AddressStreet1LTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAddressStreet1, v))
}

// AddressStreet1Contains applies the Contains predicate on the "address_street1" field.
func AddressStreet1Contains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAddressStreet1, v))
}

// AddressStreet1HasPrefix applies the HasPrefix predicate on the "address_street1" field.
func AddressStreet1HasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAddressStreet1, v))
}

// AddressStreet1HasSuffix applies the HasSuffix predicate on the "address_street1" field.
func AddressStreet1HasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAddressStreet1, v))
}

// AddressStreet1IsNil applies the IsNil predicate on the "address_street1" field.
func AddressStreet1IsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAddressStreet1))
}

// AddressStreet1NotNil applies the NotNil predicate on the "address_street1" field.
func AddressStreet1NotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAddressStreet1))
}

// AddressStreet1EqualFold applies the EqualFold predicate on the "address_street1" field.
func AddressStreet1EqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAddressStreet1, v))
}

// AddressStreet1ContainsFold applies the ContainsFold predicate on the "address_street1" field.
func AddressStreet1ContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAddressStreet1, v))
}

// AddressStreet2EQ applies the EQ predicate on the "address_street2" field.
func AddressStreet2EQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAddressStreet2, v))
}

// AddressStreet2NEQ applies the NEQ predicate on the "address_street2" field.
func AddressStreet2NEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAddressStreet2, v))
}

// AddressStreet2In applies the In predicate on the "address_street2" field.
func AddressStreet2In(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAddressStreet2, vs...))
}

// AddressStreet2NotIn applies the NotIn predicate on the "address_street2" field.
func AddressStreet2NotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAddressStreet2, vs...))
}

// AddressStreet2GT applies the GT predicate on the "address_street2" field.
func AddressStreet2GT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAddressStreet2, v))
}

// AddressStreet2GTE applies the GTE predicate on the "address_street2" field.
func AddressStreet2GTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAddressStreet2, v))
}

// AddressStreet2LT applies the LT predicate on the "address_street2" field.
func AddressStreet2LT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAddressStreet2, v))
}

// AddressStreet2LTE applies the LTE predicate on the "address_street2" field.
func AddressStreet2LTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAddressStreet2, v))
}

// AddressStreet2Contains applies the Contains predicate on the "address_street2" field.
func AddressStreet2Contains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAddressStreet2, v))
}

// AddressStreet2HasPrefix applies the HasPrefix predicate on the "address_street2" field.
func AddressStreet2HasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAddressStreet2, v))
}

// AddressStreet2HasSuffix applies the HasSuffix predicate on the "address_street2" field.
func AddressStreet2HasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAddressStreet2, v))
}

// AddressStreet2IsNil applies the IsNil predicate on the "address_street2" field.
func AddressStreet2IsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAddressStreet2))
}

// AddressStreet2NotNil applies the NotNil predicate on the "address_street2" field.
func AddressStreet2NotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAddressStreet2))
}

// AddressStreet2EqualFold applies the EqualFold predicate on the "address_street2" field.
func AddressStreet2EqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAddressStreet2, v))
}

// AddressStreet2ContainsFold applies the ContainsFold predicate on the "address_street2" field.
func AddressStreet2ContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAddressStreet2, v))
}

// AddressCityEQ applies the EQ predicate on the "address_city" field.
func AddressCityEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAddressCity, v))
}

// AddressCityNEQ applies the NEQ predicate on the "address_city" field.
func AddressCityNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAddressCity, v))
}

// AddressCityIn applies the In predicate on the "address_city" field.
func AddressCityIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAddressCity, vs...))
}

// AddressCityNotIn applies the NotIn predicate on the "address_city" field.
func AddressCityNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAddressCity, vs...))
}

// AddressCityGT applies the GT predicate on the "address_city" field.
func AddressCityGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAddressCity, v))
}

// AddressCityGTE applies the GTE predicate on the "address_city" field.
func AddressCityGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAddressCity, v))
}

// AddressCityLT applies the LT predicate on the "address_city" field.
func AddressCityLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAddressCity, v))
}

// AddressCityLTE applies the LTE predicate on the "address_city" field.
func AddressCityLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAddressCity, v))
}

// AddressCityContains applies the Contains predicate on the "address_city" field.
func AddressCityContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAddressCity, v))
}

// AddressCityHasPrefix applies the HasPrefix predicate on the "address_city" field.
func AddressCityHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAddressCity, v))
}

// AddressCityHasSuffix applies the HasSuffix predicate on the "address_city" field.
func AddressCityHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAddressCity, v))
}

// AddressCityIsNil applies the IsNil predicate on the "address_city" field.
func AddressCityIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAddressCity))
}

// AddressCityNotNil applies the NotNil predicate on the "address_city" field.
func AddressCityNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAddressCity))
}

// AddressCityEqualFold applies the EqualFold predicate on the "address_city" field.
func AddressCityEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAddressCity, v))
}

// AddressCityContainsFold applies the ContainsFold predicate on the "address_city" field.
func AddressCityContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAddressCity, v))
}

// AddressStateEQ applies the EQ predicate on the "address_state" field.
func AddressStateEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAddressState, v))
}

// AddressStateNEQ applies the NEQ predicate on the "address_state" field.
func AddressStateNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAddressState, v))
}

// AddressStateIn applies the In predicate on the "address_state" field.
func AddressStateIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAddressState, vs...))
}

// AddressStateNotIn applies the NotIn predicate on the "address_state" field.
func AddressStateNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAddressState, vs...))
}

// AddressStateGT applies the GT predicate on the "address_state" field.
func AddressStateGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAddressState, v))
}

// AddressStateGTE applies the GTE predicate on the "address_state" field.
func AddressStateGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAddressState, v))
}

// AddressStateLT applies the LT predicate on the "address_state" field.
func AddressStateLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAddressState, v))
}

// AddressStateLTE applies the LTE predicate on the "address_state" field.
func AddressStateLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAddressState, v))
}

// AddressStateContains applies the Contains predicate on the "address_state" field.
func AddressStateContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAddressState, v))
}

// AddressStateHasPrefix applies the HasPrefix predicate on the "address_state" field.
func AddressStateHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAddressState, v))
}

// AddressStateHasSuffix applies the HasSuffix predicate on the "address_state" field.
func AddressStateHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAddressState, v))
}

// AddressStateIsNil applies the IsNil predicate on the "address_state" field.
func AddressStateIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAddressState))
}

// AddressStateNotNil applies the NotNil predicate on the "address_state" field.
func AddressStateNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAddressState))
}

// AddressStateEqualFold applies the EqualFold predicate on the "address_state" field.
func AddressStateEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAddressState, v))
}

// AddressStateContainsFold applies the ContainsFold predicate on the "address_state" field.
func AddressStateContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAddressState, v))
}

// AddressZipEQ applies the EQ predicate on the "address_zip" field.
func AddressZipEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAddressZip, v))
}

// AddressZipNEQ applies the NEQ predicate on the "address_zip" field.
func AddressZipNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAddressZip, v))
}

// AddressZipIn applies the In predicate on the "address_zip" field.
func AddressZipIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAddressZip, vs...))
}

// AddressZipNotIn applies the NotIn predicate on the "address_zip" field.
func AddressZipNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAddressZip, vs...))
}

// AddressZipGT applies the GT predicate on the "address_zip" field.
func AddressZipGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAddressZip, v))
}

// AddressZipGTE applies the GTE predicate on the "address_zip" field.
func AddressZipGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAddressZip, v))
}

// AddressZipLT applies the LT predicate on the "address_zip" field.
func AddressZipLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAddressZip, v))
}

// AddressZipLTE applies the LTE predicate on the "address_zip" field.
func AddressZipLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAddressZip, v))
}

// AddressZipContains applies the Contains predicate on the "address_zip" field.
func AddressZipContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAddressZip, v))
}

// AddressZipHasPrefix applies the HasPrefix predicate on the "address_zip" field.
func AddressZipHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAddressZip, v))
}

// AddressZipHasSuffix applies the HasSuffix predicate on the "address_zip" field.
func AddressZipHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAddressZip, v))
}

// AddressZipIsNil applies the IsNil predicate on the "address_zip" field.
func AddressZipIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAddressZip))
}

// AddressZipNotNil applies the NotNil predicate on the "address_zip" field.
func AddressZipNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAddressZip))
}

// AddressZipEqualFold applies the EqualFold predicate on the "address_zip" field.
func AddressZipEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAddressZip, v))
}

// AddressZipContainsFold applies the ContainsFold predicate on the "address_zip" field.
func AddressZipContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAddressZip, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPrescriptions applies the HasEdge predicate on the "prescriptions" edge.
func HasPrescriptions() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PrescriptionsTable, PrescriptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrescriptionsWith applies the HasEdge predicate on the "prescriptions" edge with a given conditions (other predicates).
func HasPrescriptionsWith(preds ...predicate.Prescription) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newPrescriptionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
