// Code generated by ent, DO NOT EDIT.

package offer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the offer type in the database.
	Label = "offer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrescriptionID holds the string denoting the prescription_id field in the database.
	FieldPrescriptionID = "prescription_id"
	// FieldPriceCents holds the string denoting the price_cents field in the database.
	FieldPriceCents = "price_cents"
	// FieldPharmacyID holds the string denoting the pharmacy_id field in the database.
	FieldPharmacyID = "pharmacy_id"
	// FieldPharmacyItemID holds the string denoting the pharmacy_item_id field in the database.
	FieldPharmacyItemID = "pharmacy_item_id"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePrescription holds the string denoting the prescription edge name in mutations.
	EdgePrescription = "prescription"
	// EdgePharmacy holds the string denoting the pharmacy edge name in mutations.
	EdgePharmacy = "pharmacy"
	// Table holds the table name of the offer in the database.
	Table = "offers"
	// PrescriptionTable is the table that holds the prescription relation/edge.
	PrescriptionTable = "offers"
	// PrescriptionInverseTable is the table name for the Prescription entity.
	// It exists in this package in order to avoid circular dependency with the "prescription" package.
	PrescriptionInverseTable = "prescriptions"
	// PrescriptionColumn is the table column denoting the prescription relation/edge.
	PrescriptionColumn = "prescription_id"
	// PharmacyTable is the table that holds the pharmacy relation/edge.
	PharmacyTable = "offers"
	// PharmacyInverseTable is the table name for the Pharmacy entity.
	// It exists in this package in order to avoid circular dependency with the "pharmacy" package.
	PharmacyInverseTable = "pharmacies"
	// PharmacyColumn is the table column denoting the pharmacy relation/edge.
	PharmacyColumn = "pharmacy_id"
)

// Columns holds all SQL columns for offer fields.
var Columns = []string{
	FieldID,
	FieldPrescriptionID,
	FieldPriceCents,
	FieldPharmacyID,
	FieldPharmacyItemID,
	FieldExpiresAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PriceCentsValidator is a validator for the "price_cents" field. It is called by the builders before save.
	PriceCentsValidator func(int64) error
	// PharmacyItemIDValidator is a validator for the "pharmacy_item_id" field. It is called by the builders before save.
	PharmacyItemIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Offer queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPrescriptionID orders the results by the prescription_id field.
func ByPrescriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrescriptionID, opts...).ToFunc()
}

// ByPriceCents orders the results by the price_cents field.
func ByPriceCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceCents, opts...).ToFunc()
}

// ByPharmacyID orders the results by the pharmacy_id field.
func ByPharmacyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPharmacyID, opts...).ToFunc()
}

// ByPharmacyItemID orders the results by the pharmacy_item_id field.
func ByPharmacyItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPharmacyItemID, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPrescriptionField orders the results by prescription field.
func ByPrescriptionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrescriptionStep(), sql.OrderByField(field, opts...))
	}
}

// ByPharmacyField orders the results by pharmacy field.
func ByPharmacyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPharmacyStep(), sql.OrderByField(field, opts...))
	}
}
func newPrescriptionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrescriptionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PrescriptionTable, PrescriptionColumn),
	)
}
func newPharmacyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PharmacyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PharmacyTable, PharmacyColumn),
	)
}
