// Code generated by ent, DO NOT EDIT.

package offer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/LoneWolfPR/MedMarket/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldLTE(FieldID, id))
}

// PrescriptionID applies equality check predicate on the "prescription_id" field. It's identical to PrescriptionIDEQ.
func PrescriptionID(v uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldPrescriptionID, v))
}

// PriceCents applies equality check predicate on the "price_cents" field. It's identical to PriceCentsEQ.
func PriceCents(v int64) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldPriceCents, v))
}

// PharmacyID applies equality check predicate on the "pharmacy_id" field. It's identical to PharmacyIDEQ.
func PharmacyID(v uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldPharmacyID, v))
}

// PharmacyItemID applies equality check predicate on the "pharmacy_item_id" field. It's identical to PharmacyItemIDEQ.
func PharmacyItemID(v string) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldPharmacyItemID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldUpdatedAt, v))
}

// PrescriptionIDEQ applies the EQ predicate on the "prescription_id" field.
func PrescriptionIDEQ(v uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldPrescriptionID, v))
}

// PrescriptionIDNEQ applies the NEQ predicate on the "prescription_id" field.
func PrescriptionIDNEQ(v uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldNEQ(FieldPrescriptionID, v))
}

// PrescriptionIDIn applies the In predicate on the "prescription_id" field.
func PrescriptionIDIn(vs ...uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldIn(FieldPrescriptionID, vs...))
}

// PrescriptionIDNotIn applies the NotIn predicate on the "prescription_id" field.
func PrescriptionIDNotIn(vs ...uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldNotIn(FieldPrescriptionID, vs...))
}

// PriceCentsEQ applies the EQ predicate on the "price_cents" field.
func PriceCentsEQ(v int64) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldPriceCents, v))
}

// PriceCentsNEQ applies the NEQ predicate on the "price_cents" field.
func PriceCentsNEQ(v int64) predicate.Offer {
	return predicate.Offer(sql.FieldNEQ(FieldPriceCents, v))
}

// PriceCentsIn applies the In predicate on the "price_cents" field.
func PriceCentsIn(vs ...int64) predicate.Offer {
	return predicate.Offer(sql.FieldIn(FieldPriceCents, vs...))
}

// PriceCentsNotIn applies the NotIn predicate on the "price_cents" field.
func PriceCentsNotIn(vs ...int64) predicate.Offer {
	return predicate.Offer(sql.FieldNotIn(FieldPriceCents, vs...))
}

// PriceCentsGT applies the GT predicate on the "price_cents" field.
func PriceCentsGT(v int64) predicate.Offer {
	return predicate.Offer(sql.FieldGT(FieldPriceCents, v))
}

// PriceCentsGTE applies the GTE predicate on the "price_cents" field.
func PriceCentsGTE(v int64) predicate.Offer {
	return predicate.Offer(sql.FieldGTE(FieldPriceCents, v))
}

// PriceCentsLT applies the LT predicate on the "price_cents" field.
func PriceCentsLT(v int64) predicate.Offer {
	return predicate.Offer(sql.FieldLT(FieldPriceCents, v))
}

// PriceCentsLTE applies the LTE predicate on the "price_cents" field.
func PriceCentsLTE(v int64) predicate.Offer {
	return predicate.Offer(sql.FieldLTE(FieldPriceCents, v))
}

// PharmacyIDEQ applies the EQ predicate on the "pharmacy_id" field.
func PharmacyIDEQ(v uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldPharmacyID, v))
}

// PharmacyIDNEQ applies the NEQ predicate on the "pharmacy_id" field.
func PharmacyIDNEQ(v uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldNEQ(FieldPharmacyID, v))
}

// PharmacyIDIn applies the In predicate on the "pharmacy_id" field.
func PharmacyIDIn(vs ...uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldIn(FieldPharmacyID, vs...))
}

// PharmacyIDNotIn applies the NotIn predicate on the "pharmacy_id" field.
func PharmacyIDNotIn(vs ...uuid.UUID) predicate.Offer {
	return predicate.Offer(sql.FieldNotIn(FieldPharmacyID, vs...))
}

// PharmacyItemIDEQ applies the EQ predicate on the "pharmacy_item_id" field.
func PharmacyItemIDEQ(v string) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldPharmacyItemID, v))
}

// PharmacyItemIDNEQ applies the NEQ predicate on the "pharmacy_item_id" field.
func PharmacyItemIDNEQ(v string) predicate.Offer {
	return predicate.Offer(sql.FieldNEQ(FieldPharmacyItemID, v))
}

// PharmacyItemIDIn applies the In predicate on the "pharmacy_item_id" field.
func PharmacyItemIDIn(vs ...string) predicate.Offer {
	return predicate.Offer(sql.FieldIn(FieldPharmacyItemID, vs...))
}

// PharmacyItemIDNotIn applies the NotIn predicate on the "pharmacy_item_id" field.
func PharmacyItemIDNotIn(vs ...string) predicate.Offer {
	return predicate.Offer(sql.FieldNotIn(FieldPharmacyItemID, vs...))
}

// PharmacyItemIDGT applies the GT predicate on the "pharmacy_item_id" field.
func PharmacyItemIDGT(v string) predicate.Offer {
	return predicate.Offer(sql.FieldGT(FieldPharmacyItemID, v))
}

// PharmacyItemIDGTE applies the GTE predicate on the "pharmacy_item_id" field.
func PharmacyItemIDGTE(v string) predicate.Offer {
	return predicate.Offer(sql.FieldGTE(FieldPharmacyItemID, v))
}

// PharmacyItemIDLT applies the LT predicate on the "pharmacy_item_id" field.
func PharmacyItemIDLT(v string) predicate.Offer {
	return predicate.Offer(sql.FieldLT(FieldPharmacyItemID, v))
}

// PharmacyItemIDLTE applies the LTE predicate on the "pharmacy_item_id" field.
func PharmacyItemIDLTE(v string) predicate.Offer {
	return predicate.Offer(sql.FieldLTE(FieldPharmacyItemID, v))
}

// PharmacyItemIDContains applies the Contains predicate on the "pharmacy_item_id" field.
func PharmacyItemIDContains(v string) predicate.Offer {
	return predicate.Offer(sql.FieldContains(FieldPharmacyItemID, v))
}

// PharmacyItemIDHasPrefix applies the HasPrefix predicate on the "pharmacy_item_id" field.
func PharmacyItemIDHasPrefix(v string) predicate.Offer {
	return predicate.Offer(sql.FieldHasPrefix(FieldPharmacyItemID, v))
}

// PharmacyItemIDHasSuffix applies the HasSuffix predicate on the "pharmacy_item_id" field.
func PharmacyItemIDHasSuffix(v string) predicate.Offer {
	return predicate.Offer(sql.FieldHasSuffix(FieldPharmacyItemID, v))
}

// PharmacyItemIDEqualFold applies the EqualFold predicate on the "pharmacy_item_id" field.
func PharmacyItemIDEqualFold(v string) predicate.Offer {
	return predicate.Offer(sql.FieldEqualFold(FieldPharmacyItemID, v))
}

// PharmacyItemIDContainsFold applies the ContainsFold predicate on the "pharmacy_item_id" field.
func PharmacyItemIDContainsFold(v string) predicate.Offer {
	return predicate.Offer(sql.FieldContainsFold(FieldPharmacyItemID, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Offer {
	return predicate.Offer(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPrescription applies the HasEdge predicate on the "prescription" edge.
func HasPrescription() predicate.Offer {
	return predicate.Offer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PrescriptionTable, PrescriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrescriptionWith applies the HasEdge predicate on the "prescription" edge with a given conditions (other predicates).
func HasPrescriptionWith(preds ...predicate.Prescription) predicate.Offer {
	return predicate.Offer(func(s *sql.Selector) {
		step := newPrescriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPharmacy applies the HasEdge predicate on the "pharmacy" edge.
func HasPharmacy() predicate.Offer {
	return predicate.Offer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PharmacyTable, PharmacyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPharmacyWith applies the HasEdge predicate on the "pharmacy" edge with a given conditions (other predicates).
func HasPharmacyWith(preds ...predicate.Pharmacy) predicate.Offer {
	return predicate.Offer(func(s *sql.Selector) {
		step := newPharmacyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrders applies the HasEdge predicate on the "orders" edge.
func HasOrders() predicate.Offer {
	return predicate.Offer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrdersWith applies the HasEdge predicate on the "orders" edge with a given conditions (other predicates).
func HasOrdersWith(preds ...predicate.Order) predicate.Offer {
	return predicate.Offer(func(s *sql.Selector) {
		step := newOrdersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Offer) predicate.Offer {
	return predicate.Offer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Offer) predicate.Offer {
	return predicate.Offer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Offer) predicate.Offer {
	return predicate.Offer(sql.NotPredicates(p))
}
