// Code generated by ent, DO NOT EDIT.

package order

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the order type in the database.
	Label = "order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrescriptionID holds the string denoting the prescription_id field in the database.
	FieldPrescriptionID = "prescription_id"
	// FieldOfferID holds the string denoting the offer_id field in the database.
	FieldOfferID = "offer_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPharmacyOrderID holds the string denoting the pharmacy_order_id field in the database.
	FieldPharmacyOrderID = "pharmacy_order_id"
	// FieldTrackingID holds the string denoting the tracking_id field in the database.
	FieldTrackingID = "tracking_id"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldPricePaidCents holds the string denoting the price_paid_cents field in the database.
	FieldPricePaidCents = "price_paid_cents"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePrescription holds the string denoting the prescription edge name in mutations.
	EdgePrescription = "prescription"
	// EdgeOffer holds the string denoting the offer edge name in mutations.
	EdgeOffer = "offer"
	// Table holds the table name of the order in the database.
	Table = "orders"
	// PrescriptionTable is the table that holds the prescription relation/edge.
	PrescriptionTable = "orders"
	// PrescriptionInverseTable is the table name for the Prescription entity.
	// It exists in this package in order to avoid circular dependency with the "prescription" package.
	PrescriptionInverseTable = "prescriptions"
	// PrescriptionColumn is the table column denoting the prescription relation/edge.
	PrescriptionColumn = "prescription_id"
	// OfferTable is the table that holds the offer relation/edge.
	OfferTable = "orders"
	// OfferInverseTable is the table name for the Offer entity.
	// It exists in this package in order to avoid circular dependency with the "offer" package.
	OfferInverseTable = "offers"
	// OfferColumn is the table column denoting the offer relation/edge.
	OfferColumn = "offer_id"
)

// Columns holds all SQL columns for order fields.
var Columns = []string{
	FieldID,
	FieldPrescriptionID,
	FieldOfferID,
	FieldStatus,
	FieldPharmacyOrderID,
	FieldTrackingID,
	FieldQuantity,
	FieldPricePaidCents,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	QuantityValidator func(int) error
	// PricePaidCentsValidator is a validator for the "price_paid_cents" field. It is called by the builders before save.
	PricePaidCentsValidator func(int64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Order queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPrescriptionID orders the results by the prescription_id field.
func ByPrescriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrescriptionID, opts...).ToFunc()
}

// ByOfferID orders the results by the offer_id field.
func ByOfferID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOfferID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPharmacyOrderID orders the results by the pharmacy_order_id field.
func ByPharmacyOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPharmacyOrderID, opts...).ToFunc()
}

// ByTrackingID orders the results by the tracking_id field.
func ByTrackingID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrackingID, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByPricePaidCents orders the results by the price_paid_cents field.
func ByPricePaidCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricePaidCents, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPrescriptionField orders the results by prescription field.
func ByPrescriptionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrescriptionStep(), sql.OrderByField(field, opts...))
	}
}

// ByOfferField orders the results by offer field.
func ByOfferField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOfferStep(), sql.OrderByField(field, opts...))
	}
}
func newPrescriptionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrescriptionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PrescriptionTable, PrescriptionColumn),
	)
}
func newOfferStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OfferInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OfferTable, OfferColumn),
	)
}
