// Code generated by ent, DO NOT EDIT.

package order

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/LoneWolfPR/MedMarket/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldID, id))
}

// PrescriptionID applies equality check predicate on the "prescription_id" field. It's identical to PrescriptionIDEQ.
func PrescriptionID(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPrescriptionID, v))
}

// OfferID applies equality check predicate on the "offer_id" field. It's identical to OfferIDEQ.
func OfferID(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldOfferID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldStatus, v))
}

// PharmacyOrderID applies equality check predicate on the "pharmacy_order_id" field. It's identical to PharmacyOrderIDEQ.
func PharmacyOrderID(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPharmacyOrderID, v))
}

// TrackingID applies equality check predicate on the "tracking_id" field. It's identical to TrackingIDEQ.
func TrackingID(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldTrackingID, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldQuantity, v))
}

// PricePaidCents applies equality check predicate on the "price_paid_cents" field. It's identical to PricePaidCentsEQ.
func PricePaidCents(v int64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPricePaidCents, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUpdatedAt, v))
}

// PrescriptionIDEQ applies the EQ predicate on the "prescription_id" field.
func PrescriptionIDEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPrescriptionID, v))
}

// PrescriptionIDNEQ applies the NEQ predicate on the "prescription_id" field.
func PrescriptionIDNEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldPrescriptionID, v))
}

// PrescriptionIDIn applies the In predicate on the "prescription_id" field.
func PrescriptionIDIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldPrescriptionID, vs...))
}

// PrescriptionIDNotIn applies the NotIn predicate on the "prescription_id" field.
func PrescriptionIDNotIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldPrescriptionID, vs...))
}

// OfferIDEQ applies the EQ predicate on the "offer_id" field.
func OfferIDEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldOfferID, v))
}

// OfferIDNEQ applies the NEQ predicate on the "offer_id" field.
func OfferIDNEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldOfferID, v))
}

// OfferIDIn applies the In predicate on the "offer_id" field.
func OfferIDIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldOfferID, vs...))
}

// OfferIDNotIn applies the NotIn predicate on the "offer_id" field.
func OfferIDNotIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldOfferID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldStatus, v))
}

// PharmacyOrderIDEQ applies the EQ predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPharmacyOrderID, v))
}

// PharmacyOrderIDNEQ applies the NEQ predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldPharmacyOrderID, v))
}

// PharmacyOrderIDIn applies the In predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldPharmacyOrderID, vs...))
}

// PharmacyOrderIDNotIn applies the NotIn predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldPharmacyOrderID, vs...))
}

// PharmacyOrderIDGT applies the GT predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldPharmacyOrderID, v))
}

// PharmacyOrderIDGTE applies the GTE predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldPharmacyOrderID, v))
}

// PharmacyOrderIDLT applies the LT predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldPharmacyOrderID, v))
}

// PharmacyOrderIDLTE applies the LTE predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldPharmacyOrderID, v))
}

// PharmacyOrderIDContains applies the Contains predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldPharmacyOrderID, v))
}

// PharmacyOrderIDHasPrefix applies the HasPrefix predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldPharmacyOrderID, v))
}

// PharmacyOrderIDHasSuffix applies the HasSuffix predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldPharmacyOrderID, v))
}

// PharmacyOrderIDIsNil applies the IsNil predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldPharmacyOrderID))
}

// PharmacyOrderIDNotNil applies the NotNil predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldPharmacyOrderID))
}

// PharmacyOrderIDEqualFold applies the EqualFold predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldPharmacyOrderID, v))
}

// PharmacyOrderIDContainsFold applies the ContainsFold predicate on the "pharmacy_order_id" field.
func PharmacyOrderIDContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldPharmacyOrderID, v))
}

// TrackingIDEQ applies the EQ predicate on the "tracking_id" field.
func TrackingIDEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldTrackingID, v))
}

// TrackingIDNEQ applies the NEQ predicate on the "tracking_id" field.
func TrackingIDNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldTrackingID, v))
}

// TrackingIDIn applies the In predicate on the "tracking_id" field.
func TrackingIDIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldTrackingID, vs...))
}

// TrackingIDNotIn applies the NotIn predicate on the "tracking_id" field.
func TrackingIDNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldTrackingID, vs...))
}

// TrackingIDGT applies the GT predicate on the "tracking_id" field.
func TrackingIDGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldTrackingID, v))
}

// TrackingIDGTE applies the GTE predicate on the "tracking_id" field.
func TrackingIDGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldTrackingID, v))
}

// TrackingIDLT applies the LT predicate on the "tracking_id" field.
func TrackingIDLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldTrackingID, v))
}

// TrackingIDLTE applies the LTE predicate on the "tracking_id" field.
func TrackingIDLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldTrackingID, v))
}

// TrackingIDContains applies the Contains predicate on the "tracking_id" field.
func TrackingIDContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldTrackingID, v))
}

// TrackingIDHasPrefix applies the HasPrefix predicate on the "tracking_id" field.
func TrackingIDHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldTrackingID, v))
}

// TrackingIDHasSuffix applies the HasSuffix predicate on the "tracking_id" field.
func TrackingIDHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldTrackingID, v))
}

// TrackingIDIsNil applies the IsNil predicate on the "tracking_id" field.
func TrackingIDIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldTrackingID))
}

// TrackingIDNotNil applies the NotNil predicate on the "tracking_id" field.
func TrackingIDNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldTrackingID))
}

// TrackingIDEqualFold applies the EqualFold predicate on the "tracking_id" field.
func TrackingIDEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldTrackingID, v))
}

// TrackingIDContainsFold applies the ContainsFold predicate on the "tracking_id" field.
func TrackingIDContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldTrackingID, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldQuantity, v))
}

// PricePaidCentsEQ applies the EQ predicate on the "price_paid_cents" field.
func PricePaidCentsEQ(v int64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPricePaidCents, v))
}

// PricePaidCentsNEQ applies the NEQ predicate on the "price_paid_cents" field.
func PricePaidCentsNEQ(v int64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldPricePaidCents, v))
}

// PricePaidCentsIn applies the In predicate on the "price_paid_cents" field.
func PricePaidCentsIn(vs ...int64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldPricePaidCents, vs...))
}

// PricePaidCentsNotIn applies the NotIn predicate on the "price_paid_cents" field.
func PricePaidCentsNotIn(vs ...int64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldPricePaidCents, vs...))
}

// PricePaidCentsGT applies the GT predicate on the "price_paid_cents" field.
func PricePaidCentsGT(v int64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldPricePaidCents, v))
}

// PricePaidCentsGTE applies the GTE predicate on the "price_paid_cents" field.
func PricePaidCentsGTE(v int64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldPricePaidCents, v))
}

// PricePaidCentsLT applies the LT predicate on the "price_paid_cents" field.
func PricePaidCentsLT(v int64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldPricePaidCents, v))
}

// PricePaidCentsLTE applies the LTE predicate on the "price_paid_cents" field.
func PricePaidCentsLTE(v int64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldPricePaidCents, v))
}

// PricePaidCentsIsNil applies the IsNil predicate on the "price_paid_cents" field.
func PricePaidCentsIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldPricePaidCents))
}

// PricePaidCentsNotNil applies the NotNil predicate on the "price_paid_cents" field.
func PricePaidCentsNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldPricePaidCents))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPrescription applies the HasEdge predicate on the "prescription" edge.
func HasPrescription() predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PrescriptionTable, PrescriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrescriptionWith applies the HasEdge predicate on the "prescription" edge with a given conditions (other predicates).
func HasPrescriptionWith(preds ...predicate.Prescription) predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := newPrescriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOffer applies the HasEdge predicate on the "offer" edge.
func HasOffer() predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OfferTable, OfferColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOfferWith applies the HasEdge predicate on the "offer" edge with a given conditions (other predicates).
func HasOfferWith(preds ...predicate.Offer) predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := newOfferStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Order) predicate.Order {
	return predicate.Order(sql.NotPredicates(p))
}
