// Code generated by ent, DO NOT EDIT.

package pharmacy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/LoneWolfPR/MedMarket/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldName, v))
}

// ContactPhone applies equality check predicate on the "contact_phone" field. It's identical to ContactPhoneEQ.
func ContactPhone(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldContactPhone, v))
}

// Npi applies equality check predicate on the "npi" field. It's identical to NpiEQ.
func Npi(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldNpi, v))
}

// Dea applies equality check predicate on the "dea" field. It's identical to DeaEQ.
func Dea(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldDea, v))
}

// Ncpdp applies equality check predicate on the "ncpdp" field. It's identical to NcpdpEQ.
func Ncpdp(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldNcpdp, v))
}

// AddressStreet1 applies equality check predicate on the "address_street1" field. It's identical to AddressStreet1EQ.
func AddressStreet1(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldAddressStreet1, v))
}

// AddressStreet2 applies equality check predicate on the "address_street2" field. It's identical to AddressStreet2EQ.
func AddressStreet2(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldAddressStreet2, v))
}

// AddressCity applies equality check predicate on the "address_city" field. It's identical to AddressCityEQ.
func AddressCity(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldAddressCity, v))
}

// AddressState applies equality check predicate on the "address_state" field. It's identical to AddressStateEQ.
func AddressState(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldAddressState, v))
}

// AddressZip applies equality check predicate on the "address_zip" field. It's identical to AddressZipEQ.
func AddressZip(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldAddressZip, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContainsFold(FieldName, v))
}

// ContactPhoneEQ applies the EQ predicate on the "contact_phone" field.
func ContactPhoneEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldContactPhone, v))
}

// ContactPhoneNEQ applies the NEQ predicate on the "contact_phone" field.
func ContactPhoneNEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNEQ(FieldContactPhone, v))
}

// ContactPhoneIn applies the In predicate on the "contact_phone" field.
func ContactPhoneIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldIn(FieldContactPhone, vs...))
}

// ContactPhoneNotIn applies the NotIn predicate on the "contact_phone" field.
func ContactPhoneNotIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNotIn(FieldContactPhone, vs...))
}

// ContactPhoneGT applies the GT predicate on the "contact_phone" field.
func ContactPhoneGT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGT(FieldContactPhone, v))
}

// ContactPhoneGTE applies the GTE predicate on the "contact_phone" field.
func ContactPhoneGTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGTE(FieldContactPhone, v))
}

// ContactPhoneLT applies the LT predicate on the "contact_phone" field.
func ContactPhoneLT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLT(FieldContactPhone, v))
}

// ContactPhoneLTE applies the LTE predicate on the "contact_phone" field.
func ContactPhoneLTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLTE(FieldContactPhone, v))
}

// ContactPhoneContains applies the Contains predicate on the "contact_phone" field.
func ContactPhoneContains(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContains(FieldContactPhone, v))
}

// ContactPhoneHasPrefix applies the HasPrefix predicate on the "contact_phone" field.
func ContactPhoneHasPrefix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasPrefix(FieldContactPhone, v))
}

// ContactPhoneHasSuffix applies the HasSuffix predicate on the "contact_phone" field.
func ContactPhoneHasSuffix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasSuffix(FieldContactPhone, v))
}

// ContactPhoneEqualFold applies the EqualFold predicate on the "contact_phone" field.
func ContactPhoneEqualFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEqualFold(FieldContactPhone, v))
}

// ContactPhoneContainsFold applies the ContainsFold predicate on the "contact_phone" field.
func ContactPhoneContainsFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContainsFold(FieldContactPhone, v))
}

// NpiEQ applies the EQ predicate on the "npi" field.
func NpiEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldNpi, v))
}

// NpiNEQ applies the NEQ predicate on the "npi" field.
func NpiNEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNEQ(FieldNpi, v))
}

// NpiIn applies the In predicate on the "npi" field.
func NpiIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldIn(FieldNpi, vs...))
}

// NpiNotIn applies the NotIn predicate on the "npi" field.
func NpiNotIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNotIn(FieldNpi, vs...))
}

// NpiGT applies the GT predicate on the "npi" field.
func NpiGT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGT(FieldNpi, v))
}

// NpiGTE applies the GTE predicate on the "npi" field.
func NpiGTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGTE(FieldNpi, v))
}

// NpiLT applies the LT predicate on the "npi" field.
func NpiLT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLT(FieldNpi, v))
}

// NpiLTE applies the LTE predicate on the "npi" field.
func NpiLTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLTE(FieldNpi, v))
}

// NpiContains applies the Contains predicate on the "npi" field.
func NpiContains(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContains(FieldNpi, v))
}

// NpiHasPrefix applies the HasPrefix predicate on the "npi" field.
func NpiHasPrefix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasPrefix(FieldNpi, v))
}

// NpiHasSuffix applies the HasSuffix predicate on the "npi" field.
func NpiHasSuffix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasSuffix(FieldNpi, v))
}

// NpiEqualFold applies the EqualFold predicate on the "npi" field.
func NpiEqualFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEqualFold(FieldNpi, v))
}

// NpiContainsFold applies the ContainsFold predicate on the "npi" field.
func NpiContainsFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContainsFold(FieldNpi, v))
}

// DeaEQ applies the EQ predicate on the "dea" field.
func DeaEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldDea, v))
}

// DeaNEQ applies the NEQ predicate on the "dea" field.
func DeaNEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNEQ(FieldDea, v))
}

// DeaIn applies the In predicate on the "dea" field.
func DeaIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldIn(FieldDea, vs...))
}

// DeaNotIn applies the NotIn predicate on the "dea" field.
func DeaNotIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNotIn(FieldDea, vs...))
}

// DeaGT applies the GT predicate on the "dea" field.
func DeaGT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGT(FieldDea, v))
}

// DeaGTE applies the GTE predicate on the "dea" field.
func DeaGTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGTE(FieldDea, v))
}

// DeaLT applies the LT predicate on the "dea" field.
func DeaLT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLT(FieldDea, v))
}

// DeaLTE applies the LTE predicate on the "dea" field.
func DeaLTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLTE(FieldDea, v))
}

// DeaContains applies the Contains predicate on the "dea" field.
func DeaContains(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContains(FieldDea, v))
}

// DeaHasPrefix applies the HasPrefix predicate on the "dea" field.
func DeaHasPrefix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasPrefix(FieldDea, v))
}

// DeaHasSuffix applies the HasSuffix predicate on the "dea" field.
func DeaHasSuffix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasSuffix(FieldDea, v))
}

// DeaEqualFold applies the EqualFold predicate on the "dea" field.
func DeaEqualFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEqualFold(FieldDea, v))
}

// DeaContainsFold applies the ContainsFold predicate on the "dea" field.
func DeaContainsFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContainsFold(FieldDea, v))
}

// NcpdpEQ applies the EQ predicate on the "ncpdp" field.
func NcpdpEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldNcpdp, v))
}

// NcpdpNEQ applies the NEQ predicate on the "ncpdp" field.
func NcpdpNEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNEQ(FieldNcpdp, v))
}

// NcpdpIn applies the In predicate on the "ncpdp" field.
func NcpdpIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldIn(FieldNcpdp, vs...))
}

// NcpdpNotIn applies the NotIn predicate on the "ncpdp" field.
func NcpdpNotIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNotIn(FieldNcpdp, vs...))
}

// NcpdpGT applies the GT predicate on the "ncpdp" field.
func NcpdpGT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGT(FieldNcpdp, v))
}

// NcpdpGTE applies the GTE predicate on the "ncpdp" field.
func NcpdpGTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGTE(FieldNcpdp, v))
}

// NcpdpLT applies the LT predicate on the "ncpdp" field.
func NcpdpLT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLT(FieldNcpdp, v))
}

// NcpdpLTE applies the LTE predicate on the "ncpdp" field.
func NcpdpLTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLTE(FieldNcpdp, v))
}

// NcpdpContains applies the Contains predicate on the "ncpdp" field.
func NcpdpContains(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContains(FieldNcpdp, v))
}

// NcpdpHasPrefix applies the HasPrefix predicate on the "ncpdp" field.
func NcpdpHasPrefix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasPrefix(FieldNcpdp, v))
}

// NcpdpHasSuffix applies the HasSuffix predicate on the "ncpdp" field.
func NcpdpHasSuffix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasSuffix(FieldNcpdp, v))
}

// NcpdpEqualFold applies the EqualFold predicate on the "ncpdp" field.
func NcpdpEqualFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEqualFold(FieldNcpdp, v))
}

// NcpdpContainsFold applies the ContainsFold predicate on the "ncpdp" field.
func NcpdpContainsFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContainsFold(FieldNcpdp, v))
}

// AddressStreet1EQ applies the EQ predicate on the "address_street1" field.
func AddressStreet1EQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldAddressStreet1, v))
}

// AddressStreet1NEQ applies the NEQ predicate on the "address_street1" field.
func AddressStreet1NEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNEQ(FieldAddressStreet1, v))
}

// AddressStreet1In applies the In predicate on the "address_street1" field.
func AddressStreet1In(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldIn(FieldAddressStreet1, vs...))
}

// AddressStreet1NotIn applies the NotIn predicate on the "address_street1" field.
func AddressStreet1NotIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNotIn(FieldAddressStreet1, vs...))
}

// AddressStreet1GT applies the GT predicate on the "address_street1" field.
func AddressStreet1GT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGT(FieldAddressStreet1, v))
}

// AddressStreet1GTE applies the GTE predicate on the "address_street1" field.
func AddressStreet1GTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGTE(FieldAddressStreet1, v))
}

// AddressStreet1LT applies the LT predicate on the "address_street1" field.
func AddressStreet1LT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLT(FieldAddressStreet1, v))
}

// AddressStreet1LTE applies the LTE predicate on the "address_street1" field.
func AddressStreet1LTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLTE(FieldAddressStreet1, v))
}

// AddressStreet1Contains applies the Contains predicate on the "address_street1" field.
func AddressStreet1Contains(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContains(FieldAddressStreet1, v))
}

// AddressStreet1HasPrefix applies the HasPrefix predicate on the "address_street1" field.
func AddressStreet1HasPrefix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasPrefix(FieldAddressStreet1, v))
}

// AddressStreet1HasSuffix applies the HasSuffix predicate on the "address_street1" field.
func AddressStreet1HasSuffix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasSuffix(FieldAddressStreet1, v))
}

// AddressStreet1EqualFold applies the EqualFold predicate on the "address_street1" field.
func AddressStreet1EqualFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEqualFold(FieldAddressStreet1, v))
}

// AddressStreet1ContainsFold applies the ContainsFold predicate on the "address_street1" field.
func AddressStreet1ContainsFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContainsFold(FieldAddressStreet1, v))
}

// AddressStreet2EQ applies the EQ predicate on the "address_street2" field.
func AddressStreet2EQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldAddressStreet2, v))
}

// AddressStreet2NEQ applies the NEQ predicate on the "address_street2" field.
func AddressStreet2NEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNEQ(FieldAddressStreet2, v))
}

// AddressStreet2In applies the In predicate on the "address_street2" field.
func AddressStreet2In(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldIn(FieldAddressStreet2, vs...))
}

// AddressStreet2NotIn applies the NotIn predicate on the "address_street2" field.
func AddressStreet2NotIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNotIn(FieldAddressStreet2, vs...))
}

// AddressStreet2GT applies the GT predicate on the "address_street2" field.
func AddressStreet2GT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGT(FieldAddressStreet2, v))
}

// AddressStreet2GTE applies the GTE predicate on the "address_street2" field.
func AddressStreet2GTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGTE(FieldAddressStreet2, v))
}

// AddressStreet2LT applies the LT predicate on the "address_street2" field.
func AddressStreet2LT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLT(FieldAddressStreet2, v))
}

// AddressStreet2LTE applies the LTE predicate on the "address_street2" field.
func AddressStreet2LTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLTE(FieldAddressStreet2, v))
}

// AddressStreet2Contains applies the Contains predicate on the "address_street2" field.
func AddressStreet2Contains(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContains(FieldAddressStreet2, v))
}

// AddressStreet2HasPrefix applies the HasPrefix predicate on the "address_street2" field.
func AddressStreet2HasPrefix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasPrefix(FieldAddressStreet2, v))
}

// AddressStreet2HasSuffix applies the HasSuffix predicate on the "address_street2" field.
func AddressStreet2HasSuffix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasSuffix(FieldAddressStreet2, v))
}

// AddressStreet2IsNil applies the IsNil predicate on the "address_street2" field.
func AddressStreet2IsNil() predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldIsNull(FieldAddressStreet2))
}

// AddressStreet2NotNil applies the NotNil predicate on the "address_street2" field.
func AddressStreet2NotNil() predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNotNull(FieldAddressStreet2))
}

// AddressStreet2EqualFold applies the EqualFold predicate on the "address_street2" field.
func AddressStreet2EqualFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEqualFold(FieldAddressStreet2, v))
}

// AddressStreet2ContainsFold applies the ContainsFold predicate on the "address_street2" field.
func AddressStreet2ContainsFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContainsFold(FieldAddressStreet2, v))
}

// AddressCityEQ applies the EQ predicate on the "address_city" field.
func AddressCityEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldAddressCity, v))
}

// AddressCityNEQ applies the NEQ predicate on the "address_city" field.
func AddressCityNEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNEQ(FieldAddressCity, v))
}

// AddressCityIn applies the In predicate on the "address_city" field.
func AddressCityIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldIn(FieldAddressCity, vs...))
}

// AddressCityNotIn applies the NotIn predicate on the "address_city" field.
func AddressCityNotIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNotIn(FieldAddressCity, vs...))
}

// AddressCityGT applies the GT predicate on the "address_city" field.
func AddressCityGT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGT(FieldAddressCity, v))
}

// AddressCityGTE applies the GTE predicate on the "address_city" field.
func AddressCityGTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGTE(FieldAddressCity, v))
}

// AddressCityLT applies the LT predicate on the "address_city" field.
func AddressCityLT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLT(FieldAddressCity, v))
}

// AddressCityLTE applies the LTE predicate on the "address_city" field.
func AddressCityLTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLTE(FieldAddressCity, v))
}

// AddressCityContains applies the Contains predicate on the "address_city" field.
func AddressCityContains(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContains(FieldAddressCity, v))
}

// AddressCityHasPrefix applies the HasPrefix predicate on the "address_city" field.
func AddressCityHasPrefix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasPrefix(FieldAddressCity, v))
}

// AddressCityHasSuffix applies the HasSuffix predicate on the "address_city" field.
func AddressCityHasSuffix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasSuffix(FieldAddressCity, v))
}

// AddressCityEqualFold applies the EqualFold predicate on the "address_city" field.
func AddressCityEqualFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEqualFold(FieldAddressCity, v))
}

// AddressCityContainsFold applies the ContainsFold predicate on the "address_city" field.
func AddressCityContainsFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContainsFold(FieldAddressCity, v))
}

// AddressStateEQ applies the EQ predicate on the "address_state" field.
func AddressStateEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldAddressState, v))
}

// AddressStateNEQ applies the NEQ predicate on the "address_state" field.
func AddressStateNEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNEQ(FieldAddressState, v))
}

// AddressStateIn applies the In predicate on the "address_state" field.
func AddressStateIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldIn(FieldAddressState, vs...))
}

// AddressStateNotIn applies the NotIn predicate on the "address_state" field.
func AddressStateNotIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNotIn(FieldAddressState, vs...))
}

// AddressStateGT applies the GT predicate on the "address_state" field.
func AddressStateGT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGT(FieldAddressState, v))
}

// AddressStateGTE applies the GTE predicate on the "address_state" field.
func AddressStateGTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGTE(FieldAddressState, v))
}

// AddressStateLT applies the LT predicate on the "address_state" field.
func AddressStateLT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLT(FieldAddressState, v))
}

// AddressStateLTE applies the LTE predicate on the "address_state" field.
func AddressStateLTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLTE(FieldAddressState, v))
}

// AddressStateContains applies the Contains predicate on the "address_state" field.
func AddressStateContains(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContains(FieldAddressState, v))
}

// AddressStateHasPrefix applies the HasPrefix predicate on the "address_state" field.
func AddressStateHasPrefix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasPrefix(FieldAddressState, v))
}

// AddressStateHasSuffix applies the HasSuffix predicate on the "address_state" field.
func AddressStateHasSuffix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasSuffix(FieldAddressState, v))
}

// AddressStateEqualFold applies the EqualFold predicate on the "address_state" field.
func AddressStateEqualFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEqualFold(FieldAddressState, v))
}

// AddressStateContainsFold applies the ContainsFold predicate on the "address_state" field.
func AddressStateContainsFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContainsFold(FieldAddressState, v))
}

// AddressZipEQ applies the EQ predicate on the "address_zip" field.
func AddressZipEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldAddressZip, v))
}

// AddressZipNEQ applies the NEQ predicate on the "address_zip" field.
func AddressZipNEQ(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNEQ(FieldAddressZip, v))
}

// AddressZipIn applies the In predicate on the "address_zip" field.
func AddressZipIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldIn(FieldAddressZip, vs...))
}

// AddressZipNotIn applies the NotIn predicate on the "address_zip" field.
func AddressZipNotIn(vs ...string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNotIn(FieldAddressZip, vs...))
}

// AddressZipGT applies the GT predicate on the "address_zip" field.
func AddressZipGT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGT(FieldAddressZip, v))
}

// AddressZipGTE applies the GTE predicate on the "address_zip" field.
func AddressZipGTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGTE(FieldAddressZip, v))
}

// AddressZipLT applies the LT predicate on the "address_zip" field.
func AddressZipLT(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLT(FieldAddressZip, v))
}

// AddressZipLTE applies the LTE predicate on the "address_zip" field.
func AddressZipLTE(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLTE(FieldAddressZip, v))
}

// AddressZipContains applies the Contains predicate on the "address_zip" field.
func AddressZipContains(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContains(FieldAddressZip, v))
}

// AddressZipHasPrefix applies the HasPrefix predicate on the "address_zip" field.
func AddressZipHasPrefix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasPrefix(FieldAddressZip, v))
}

// AddressZipHasSuffix applies the HasSuffix predicate on the "address_zip" field.
func AddressZipHasSuffix(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldHasSuffix(FieldAddressZip, v))
}

// AddressZipEqualFold applies the EqualFold predicate on the "address_zip" field.
func AddressZipEqualFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEqualFold(FieldAddressZip, v))
}

// AddressZipContainsFold applies the ContainsFold predicate on the "address_zip" field.
func AddressZipContainsFold(v string) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldContainsFold(FieldAddressZip, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Pharmacy {
	return predicate.Pharmacy(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Pharmacy) predicate.Pharmacy {
	return predicate.Pharmacy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Pharmacy) predicate.Pharmacy {
	return predicate.Pharmacy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Pharmacy) predicate.Pharmacy {
	return predicate.Pharmacy(sql.NotPredicates(p))
}
