// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LoneWolfPR/MedMarket/backend/ent/offer"
	"github.com/LoneWolfPR/MedMarket/backend/ent/pharmacy"
	"github.com/LoneWolfPR/MedMarket/backend/ent/prescription"
	"github.com/google/uuid"
)

// Offer is the model entity for the Offer schema.
type Offer struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PrescriptionID holds the value of the "prescription_id" field.
	PrescriptionID uuid.UUID `json:"prescription_id,omitempty"`
	// PriceCents holds the value of the "price_cents" field.
	PriceCents int64 `json:"price_cents,omitempty"`
	// PharmacyID holds the value of the "pharmacy_id" field.
	PharmacyID uuid.UUID `json:"pharmacy_id,omitempty"`
	// PharmacyItemID holds the value of the "pharmacy_item_id" field.
	PharmacyItemID string `json:"pharmacy_item_id,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OfferQuery when eager-loading is set.
	Edges        OfferEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OfferEdges holds the relations/edges for other nodes in the graph.
type OfferEdges struct {
	// Prescription holds the value of the prescription edge.
	Prescription *Prescription `json:"prescription,omitempty"`
	// Pharmacy holds the value of the pharmacy edge.
	Pharmacy *Pharmacy `json:"pharmacy,omitempty"`
	// Orders holds the value of the orders edge.
	Orders []*Order `json:"orders,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PrescriptionOrErr returns the Prescription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OfferEdges) PrescriptionOrErr() (*Prescription, error) {
	if e.Prescription != nil {
		return e.Prescription, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: prescription.Label}
	}
	return nil, &NotLoadedError{edge: "prescription"}
}

// PharmacyOrErr returns the Pharmacy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OfferEdges) PharmacyOrErr() (*Pharmacy, error) {
	if e.Pharmacy != nil {
		return e.Pharmacy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: pharmacy.Label}
	}
	return nil, &NotLoadedError{edge: "pharmacy"}
}

// OrdersOrErr returns the Orders value or an error if the edge
// was not loaded in eager-loading.
func (e OfferEdges) OrdersOrErr() ([]*Order, error) {
	if e.loadedTypes[2] {
		return e.Orders, nil
	}
	return nil, &NotLoadedError{edge: "orders"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Offer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case offer.FieldPriceCents:
			values[i] = new(sql.NullInt64)
		case offer.FieldPharmacyItemID:
			values[i] = new(sql.NullString)
		case offer.FieldExpiresAt, offer.FieldCreatedAt, offer.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case offer.FieldID, offer.FieldPrescriptionID, offer.FieldPharmacyID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Offer fields.
func (_m *Offer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case offer.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case offer.FieldPrescriptionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field prescription_id", values[i])
			} else if value != nil {
				_m.PrescriptionID = *value
			}
		case offer.FieldPriceCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_cents", values[i])
			} else if value.Valid {
				_m.PriceCents = value.Int64
			}
		case offer.FieldPharmacyID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field pharmacy_id", values[i])
			} else if value != nil {
				_m.PharmacyID = *value
			}
		case offer.FieldPharmacyItemID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pharmacy_item_id", values[i])
			} else if value.Valid {
				_m.PharmacyItemID = value.String
			}
		case offer.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case offer.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case offer.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Offer.
// This includes values selected through modifiers, order, etc.
func (_m *Offer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPrescription queries the "prescription" edge of the Offer entity.
func (_m *Offer) QueryPrescription() *PrescriptionQuery {
	return NewOfferClient(_m.config).QueryPrescription(_m)
}

// QueryPharmacy queries the "pharmacy" edge of the Offer entity.
func (_m *Offer) QueryPharmacy() *PharmacyQuery {
	return NewOfferClient(_m.config).QueryPharmacy(_m)
}

// QueryOrders queries the "orders" edge of the Offer entity.
func (_m *Offer) QueryOrders() *OrderQuery {
	return NewOfferClient(_m.config).QueryOrders(_m)
}

// Update returns a builder for updating this Offer.
// Note that you need to call Offer.Unwrap() before calling this method if this Offer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Offer) Update() *OfferUpdateOne {
	return NewOfferClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Offer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Offer) Unwrap() *Offer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Offer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Offer) String() string {
	var builder strings.Builder
	builder.WriteString("Offer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("prescription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrescriptionID))
	builder.WriteString(", ")
	builder.WriteString("price_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceCents))
	builder.WriteString(", ")
	builder.WriteString("pharmacy_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PharmacyID))
	builder.WriteString(", ")
	builder.WriteString("pharmacy_item_id=")
	builder.WriteString(_m.PharmacyItemID)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Offers is a parsable slice of Offer.
type Offers []*Offer
