// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LoneWolfPR/MedMarket/backend/ent/offer"
	"github.com/LoneWolfPR/MedMarket/backend/ent/pharmacy"
	"github.com/LoneWolfPR/MedMarket/backend/ent/prescription"
	"github.com/google/uuid"
)

// OfferCreate is the builder for creating a Offer entity.
type OfferCreate struct {
	config
	mutation *OfferMutation
	hooks    []Hook
}

// SetPrescriptionID sets the "prescription_id" field.
func (_c *OfferCreate) SetPrescriptionID(v uuid.UUID) *OfferCreate {
	_c.mutation.SetPrescriptionID(v)
	return _c
}

// SetPriceCents sets the "price_cents" field.
func (_c *OfferCreate) SetPriceCents(v int64) *OfferCreate {
	_c.mutation.SetPriceCents(v)
	return _c
}

// SetPharmacyID sets the "pharmacy_id" field.
func (_c *OfferCreate) SetPharmacyID(v uuid.UUID) *OfferCreate {
	_c.mutation.SetPharmacyID(v)
	return _c
}

// SetPharmacyItemID sets the "pharmacy_item_id" field.
func (_c *OfferCreate) SetPharmacyItemID(v string) *OfferCreate {
	_c.mutation.SetPharmacyItemID(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OfferCreate) SetExpiresAt(v time.Time) *OfferCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OfferCreate) SetCreatedAt(v time.Time) *OfferCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OfferCreate) SetNillableCreatedAt(v *time.Time) *OfferCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OfferCreate) SetUpdatedAt(v time.Time) *OfferCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OfferCreate) SetNillableUpdatedAt(v *time.Time) *OfferCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OfferCreate) SetID(v uuid.UUID) *OfferCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OfferCreate) SetNillableID(v *uuid.UUID) *OfferCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPrescription sets the "prescription" edge to the Prescription entity.
func (_c *OfferCreate) SetPrescription(v *Prescription) *OfferCreate {
	return _c.SetPrescriptionID(v.ID)
}

// SetPharmacy sets the "pharmacy" edge to the Pharmacy entity.
func (_c *OfferCreate) SetPharmacy(v *Pharmacy) *OfferCreate {
	return _c.SetPharmacyID(v.ID)
}

// Mutation returns the OfferMutation object of the builder.
func (_c *OfferCreate) Mutation() *OfferMutation {
	return _c.mutation
}

// Save creates the Offer in the database.
func (_c *OfferCreate) Save(ctx context.Context) (*Offer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OfferCreate) SaveX(ctx context.Context) *Offer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OfferCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OfferCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OfferCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := offer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := offer.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := offer.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OfferCreate) check() error {
	if _, ok := _c.mutation.PrescriptionID(); !ok {
		return &ValidationError{Name: "prescription_id", err: errors.New(`ent: missing required field "Offer.prescription_id"`)}
	}
	if _, ok := _c.mutation.PriceCents(); !ok {
		return &ValidationError{Name: "price_cents", err: errors.New(`ent: missing required field "Offer.price_cents"`)}
	}
	if v, ok := _c.mutation.PriceCents(); ok {
		if err := offer.PriceCentsValidator(v); err != nil {
			return &ValidationError{Name: "price_cents", err: fmt.Errorf(`ent: validator failed for field "Offer.price_cents": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PharmacyID(); !ok {
		return &ValidationError{Name: "pharmacy_id", err: errors.New(`ent: missing required field "Offer.pharmacy_id"`)}
	}
	if _, ok := _c.mutation.PharmacyItemID(); !ok {
		return &ValidationError{Name: "pharmacy_item_id", err: errors.New(`ent: missing required field "Offer.pharmacy_item_id"`)}
	}
	if v, ok := _c.mutation.PharmacyItemID(); ok {
		if err := offer.PharmacyItemIDValidator(v); err != nil {
			return &ValidationError{Name: "pharmacy_item_id", err: fmt.Errorf(`ent: validator failed for field "Offer.pharmacy_item_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "Offer.expires_at"`)}
	}
	if len(_c.mutation.PrescriptionIDs()) == 0 {
		return &ValidationError{Name: "prescription", err: errors.New(`ent: missing required edge "Offer.prescription"`)}
	}
	if len(_c.mutation.PharmacyIDs()) == 0 {
		return &ValidationError{Name: "pharmacy", err: errors.New(`ent: missing required edge "Offer.pharmacy"`)}
	}
	return nil
}

func (_c *OfferCreate) sqlSave(ctx context.Context) (*Offer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OfferCreate) createSpec() (*Offer, *sqlgraph.CreateSpec) {
	var (
		_node = &Offer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(offer.Table, sqlgraph.NewFieldSpec(offer.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PriceCents(); ok {
		_spec.SetField(offer.FieldPriceCents, field.TypeInt64, value)
		_node.PriceCents = value
	}
	if value, ok := _c.mutation.PharmacyItemID(); ok {
		_spec.SetField(offer.FieldPharmacyItemID, field.TypeString, value)
		_node.PharmacyItemID = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(offer.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(offer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(offer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PrescriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   offer.PrescriptionTable,
			Columns: []string{offer.PrescriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prescription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PrescriptionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PharmacyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   offer.PharmacyTable,
			Columns: []string{offer.PharmacyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pharmacy.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PharmacyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OfferCreateBulk is the builder for creating many Offer entities in bulk.
type OfferCreateBulk struct {
	config
	err      error
	builders []*OfferCreate
}

// Save creates the Offer entities in the database.
func (_c *OfferCreateBulk) Save(ctx context.Context) ([]*Offer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Offer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OfferMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OfferCreateBulk) SaveX(ctx context.Context) []*Offer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OfferCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OfferCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
