// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LoneWolfPR/MedMarket/backend/ent/offer"
	"github.com/LoneWolfPR/MedMarket/backend/ent/order"
	"github.com/LoneWolfPR/MedMarket/backend/ent/prescription"
	"github.com/google/uuid"
)

// Order is the model entity for the Order schema.
type Order struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PrescriptionID holds the value of the "prescription_id" field.
	PrescriptionID uuid.UUID `json:"prescription_id,omitempty"`
	// OfferID holds the value of the "offer_id" field.
	OfferID uuid.UUID `json:"offer_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// PharmacyOrderID holds the value of the "pharmacy_order_id" field.
	PharmacyOrderID string `json:"pharmacy_order_id,omitempty"`
	// TrackingID holds the value of the "tracking_id" field.
	TrackingID string `json:"tracking_id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity int `json:"quantity,omitempty"`
	// PricePaidCents holds the value of the "price_paid_cents" field.
	PricePaidCents *int64 `json:"price_paid_cents,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrderQuery when eager-loading is set.
	Edges        OrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrderEdges holds the relations/edges for other nodes in the graph.
type OrderEdges struct {
	// Prescription holds the value of the prescription edge.
	Prescription *Prescription `json:"prescription,omitempty"`
	// Offer holds the value of the offer edge.
	Offer *Offer `json:"offer,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PrescriptionOrErr returns the Prescription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderEdges) PrescriptionOrErr() (*Prescription, error) {
	if e.Prescription != nil {
		return e.Prescription, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: prescription.Label}
	}
	return nil, &NotLoadedError{edge: "prescription"}
}

// OfferOrErr returns the Offer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderEdges) OfferOrErr() (*Offer, error) {
	if e.Offer != nil {
		return e.Offer, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: offer.Label}
	}
	return nil, &NotLoadedError{edge: "offer"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Order) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case order.FieldQuantity, order.FieldPricePaidCents:
			values[i] = new(sql.NullInt64)
		case order.FieldStatus, order.FieldPharmacyOrderID, order.FieldTrackingID:
			values[i] = new(sql.NullString)
		case order.FieldCreatedAt, order.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case order.FieldID, order.FieldPrescriptionID, order.FieldOfferID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Order fields.
func (_m *Order) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case order.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case order.FieldPrescriptionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field prescription_id", values[i])
			} else if value != nil {
				_m.PrescriptionID = *value
			}
		case order.FieldOfferID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field offer_id", values[i])
			} else if value != nil {
				_m.OfferID = *value
			}
		case order.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case order.FieldPharmacyOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pharmacy_order_id", values[i])
			} else if value.Valid {
				_m.PharmacyOrderID = value.String
			}
		case order.FieldTrackingID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tracking_id", values[i])
			} else if value.Valid {
				_m.TrackingID = value.String
			}
		case order.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = int(value.Int64)
			}
		case order.FieldPricePaidCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_paid_cents", values[i])
			} else if value.Valid {
				_m.PricePaidCents = new(int64)
				*_m.PricePaidCents = value.Int64
			}
		case order.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case order.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Order.
// This includes values selected through modifiers, order, etc.
func (_m *Order) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPrescription queries the "prescription" edge of the Order entity.
func (_m *Order) QueryPrescription() *PrescriptionQuery {
	return NewOrderClient(_m.config).QueryPrescription(_m)
}

// QueryOffer queries the "offer" edge of the Order entity.
func (_m *Order) QueryOffer() *OfferQuery {
	return NewOrderClient(_m.config).QueryOffer(_m)
}

// Update returns a builder for updating this Order.
// Note that you need to call Order.Unwrap() before calling this method if this Order
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Order) Update() *OrderUpdateOne {
	return NewOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Order entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Order) Unwrap() *Order {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Order is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Order) String() string {
	var builder strings.Builder
	builder.WriteString("Order(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("prescription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrescriptionID))
	builder.WriteString(", ")
	builder.WriteString("offer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OfferID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("pharmacy_order_id=")
	builder.WriteString(_m.PharmacyOrderID)
	builder.WriteString(", ")
	builder.WriteString("tracking_id=")
	builder.WriteString(_m.TrackingID)
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	if v := _m.PricePaidCents; v != nil {
		builder.WriteString("price_paid_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Orders is a parsable slice of Order.
type Orders []*Order
