// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LoneWolfPR/MedMarket/backend/ent/order"
	"github.com/LoneWolfPR/MedMarket/backend/ent/predicate"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdate) SetStatus(v string) *OrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableStatus(v *string) *OrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPharmacyOrderID sets the "pharmacy_order_id" field.
func (_u *OrderUpdate) SetPharmacyOrderID(v string) *OrderUpdate {
	_u.mutation.SetPharmacyOrderID(v)
	return _u
}

// SetNillablePharmacyOrderID sets the "pharmacy_order_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillablePharmacyOrderID(v *string) *OrderUpdate {
	if v != nil {
		_u.SetPharmacyOrderID(*v)
	}
	return _u
}

// ClearPharmacyOrderID clears the value of the "pharmacy_order_id" field.
func (_u *OrderUpdate) ClearPharmacyOrderID() *OrderUpdate {
	_u.mutation.ClearPharmacyOrderID()
	return _u
}

// SetTrackingID sets the "tracking_id" field.
func (_u *OrderUpdate) SetTrackingID(v string) *OrderUpdate {
	_u.mutation.SetTrackingID(v)
	return _u
}

// SetNillableTrackingID sets the "tracking_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableTrackingID(v *string) *OrderUpdate {
	if v != nil {
		_u.SetTrackingID(*v)
	}
	return _u
}

// ClearTrackingID clears the value of the "tracking_id" field.
func (_u *OrderUpdate) ClearTrackingID() *OrderUpdate {
	_u.mutation.ClearTrackingID()
	return _u
}

// SetPricePaidCents sets the "price_paid_cents" field.
func (_u *OrderUpdate) SetPricePaidCents(v int64) *OrderUpdate {
	_u.mutation.ResetPricePaidCents()
	_u.mutation.SetPricePaidCents(v)
	return _u
}

// SetNillablePricePaidCents sets the "price_paid_cents" field if the given value is not nil.
func (_u *OrderUpdate) SetNillablePricePaidCents(v *int64) *OrderUpdate {
	if v != nil {
		_u.SetPricePaidCents(*v)
	}
	return _u
}

// AddPricePaidCents adds value to the "price_paid_cents" field.
func (_u *OrderUpdate) AddPricePaidCents(v int64) *OrderUpdate {
	_u.mutation.AddPricePaidCents(v)
	return _u
}

// ClearPricePaidCents clears the value of the "price_paid_cents" field.
func (_u *OrderUpdate) ClearPricePaidCents() *OrderUpdate {
	_u.mutation.ClearPricePaidCents()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdate) SetUpdatedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdate) Mutation() *OrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdate) check() error {
	if v, ok := _u.mutation.PricePaidCents(); ok {
		if err := order.PricePaidCentsValidator(v); err != nil {
			return &ValidationError{Name: "price_paid_cents", err: fmt.Errorf(`ent: validator failed for field "Order.price_paid_cents": %w`, err)}
		}
	}
	if _u.mutation.PrescriptionCleared() && len(_u.mutation.PrescriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.prescription"`)
	}
	if _u.mutation.OfferCleared() && len(_u.mutation.OfferIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.offer"`)
	}
	return nil
}

func (_u *OrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PharmacyOrderID(); ok {
		_spec.SetField(order.FieldPharmacyOrderID, field.TypeString, value)
	}
	if _u.mutation.PharmacyOrderIDCleared() {
		_spec.ClearField(order.FieldPharmacyOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.TrackingID(); ok {
		_spec.SetField(order.FieldTrackingID, field.TypeString, value)
	}
	if _u.mutation.TrackingIDCleared() {
		_spec.ClearField(order.FieldTrackingID, field.TypeString)
	}
	if value, ok := _u.mutation.PricePaidCents(); ok {
		_spec.SetField(order.FieldPricePaidCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPricePaidCents(); ok {
		_spec.AddField(order.FieldPricePaidCents, field.TypeInt64, value)
	}
	if _u.mutation.PricePaidCentsCleared() {
		_spec.ClearField(order.FieldPricePaidCents, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetStatus sets the "status" field.
func (_u *OrderUpdateOne) SetStatus(v string) *OrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableStatus(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPharmacyOrderID sets the "pharmacy_order_id" field.
func (_u *OrderUpdateOne) SetPharmacyOrderID(v string) *OrderUpdateOne {
	_u.mutation.SetPharmacyOrderID(v)
	return _u
}

// SetNillablePharmacyOrderID sets the "pharmacy_order_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillablePharmacyOrderID(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetPharmacyOrderID(*v)
	}
	return _u
}

// ClearPharmacyOrderID clears the value of the "pharmacy_order_id" field.
func (_u *OrderUpdateOne) ClearPharmacyOrderID() *OrderUpdateOne {
	_u.mutation.ClearPharmacyOrderID()
	return _u
}

// SetTrackingID sets the "tracking_id" field.
func (_u *OrderUpdateOne) SetTrackingID(v string) *OrderUpdateOne {
	_u.mutation.SetTrackingID(v)
	return _u
}

// SetNillableTrackingID sets the "tracking_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableTrackingID(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetTrackingID(*v)
	}
	return _u
}

// ClearTrackingID clears the value of the "tracking_id" field.
func (_u *OrderUpdateOne) ClearTrackingID() *OrderUpdateOne {
	_u.mutation.ClearTrackingID()
	return _u
}

// SetPricePaidCents sets the "price_paid_cents" field.
func (_u *OrderUpdateOne) SetPricePaidCents(v int64) *OrderUpdateOne {
	_u.mutation.ResetPricePaidCents()
	_u.mutation.SetPricePaidCents(v)
	return _u
}

// SetNillablePricePaidCents sets the "price_paid_cents" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillablePricePaidCents(v *int64) *OrderUpdateOne {
	if v != nil {
		_u.SetPricePaidCents(*v)
	}
	return _u
}

// AddPricePaidCents adds value to the "price_paid_cents" field.
func (_u *OrderUpdateOne) AddPricePaidCents(v int64) *OrderUpdateOne {
	_u.mutation.AddPricePaidCents(v)
	return _u
}

// ClearPricePaidCents clears the value of the "price_paid_cents" field.
func (_u *OrderUpdateOne) ClearPricePaidCents() *OrderUpdateOne {
	_u.mutation.ClearPricePaidCents()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdateOne) SetUpdatedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdateOne) Mutation() *OrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Order entity.
func (_u *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdateOne) check() error {
	if v, ok := _u.mutation.PricePaidCents(); ok {
		if err := order.PricePaidCentsValidator(v); err != nil {
			return &ValidationError{Name: "price_paid_cents", err: fmt.Errorf(`ent: validator failed for field "Order.price_paid_cents": %w`, err)}
		}
	}
	if _u.mutation.PrescriptionCleared() && len(_u.mutation.PrescriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.prescription"`)
	}
	if _u.mutation.OfferCleared() && len(_u.mutation.OfferIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.offer"`)
	}
	return nil
}

func (_u *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PharmacyOrderID(); ok {
		_spec.SetField(order.FieldPharmacyOrderID, field.TypeString, value)
	}
	if _u.mutation.PharmacyOrderIDCleared() {
		_spec.ClearField(order.FieldPharmacyOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.TrackingID(); ok {
		_spec.SetField(order.FieldTrackingID, field.TypeString, value)
	}
	if _u.mutation.TrackingIDCleared() {
		_spec.ClearField(order.FieldTrackingID, field.TypeString)
	}
	if value, ok := _u.mutation.PricePaidCents(); ok {
		_spec.SetField(order.FieldPricePaidCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPricePaidCents(); ok {
		_spec.AddField(order.FieldPricePaidCents, field.TypeInt64, value)
	}
	if _u.mutation.PricePaidCentsCleared() {
		_spec.ClearField(order.FieldPricePaidCents, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Order{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
