// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LoneWolfPR/MedMarket/backend/ent/pharmacy"
	"github.com/google/uuid"
)

// Pharmacy is the model entity for the Pharmacy schema.
type Pharmacy struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ContactPhone holds the value of the "contact_phone" field.
	ContactPhone string `json:"contact_phone,omitempty"`
	// Npi holds the value of the "npi" field.
	Npi string `json:"npi,omitempty"`
	// Dea holds the value of the "dea" field.
	Dea string `json:"dea,omitempty"`
	// Ncpdp holds the value of the "ncpdp" field.
	Ncpdp string `json:"ncpdp,omitempty"`
	// AddressStreet1 holds the value of the "address_street1" field.
	AddressStreet1 string `json:"address_street1,omitempty"`
	// AddressStreet2 holds the value of the "address_street2" field.
	AddressStreet2 string `json:"address_street2,omitempty"`
	// AddressCity holds the value of the "address_city" field.
	AddressCity string `json:"address_city,omitempty"`
	// AddressState holds the value of the "address_state" field.
	AddressState string `json:"address_state,omitempty"`
	// AddressZip holds the value of the "address_zip" field.
	AddressZip string `json:"address_zip,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PharmacyQuery when eager-loading is set.
	Edges        PharmacyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PharmacyEdges holds the relations/edges for other nodes in the graph.
type PharmacyEdges struct {
	// Offers holds the value of the offers edge.
	Offers []*Offer `json:"offers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OffersOrErr returns the Offers value or an error if the edge
// was not loaded in eager-loading.
func (e PharmacyEdges) OffersOrErr() ([]*Offer, error) {
	if e.loadedTypes[0] {
		return e.Offers, nil
	}
	return nil, &NotLoadedError{edge: "offers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Pharmacy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pharmacy.FieldCode, pharmacy.FieldName, pharmacy.FieldContactPhone, pharmacy.FieldNpi, pharmacy.FieldDea, pharmacy.FieldNcpdp, pharmacy.FieldAddressStreet1, pharmacy.FieldAddressStreet2, pharmacy.FieldAddressCity, pharmacy.FieldAddressState, pharmacy.FieldAddressZip:
			values[i] = new(sql.NullString)
		case pharmacy.FieldCreatedAt, pharmacy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case pharmacy.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Pharmacy fields.
func (_m *Pharmacy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pharmacy.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case pharmacy.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case pharmacy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case pharmacy.FieldContactPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_phone", values[i])
			} else if value.Valid {
				_m.ContactPhone = value.String
			}
		case pharmacy.FieldNpi:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field npi", values[i])
			} else if value.Valid {
				_m.Npi = value.String
			}
		case pharmacy.FieldDea:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dea", values[i])
			} else if value.Valid {
				_m.Dea = value.String
			}
		case pharmacy.FieldNcpdp:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ncpdp", values[i])
			} else if value.Valid {
				_m.Ncpdp = value.String
			}
		case pharmacy.FieldAddressStreet1:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address_street1", values[i])
			} else if value.Valid {
				_m.AddressStreet1 = value.String
			}
		case pharmacy.FieldAddressStreet2:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address_street2", values[i])
			} else if value.Valid {
				_m.AddressStreet2 = value.String
			}
		case pharmacy.FieldAddressCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address_city", values[i])
			} else if value.Valid {
				_m.AddressCity = value.String
			}
		case pharmacy.FieldAddressState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address_state", values[i])
			} else if value.Valid {
				_m.AddressState = value.String
			}
		case pharmacy.FieldAddressZip:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address_zip", values[i])
			} else if value.Valid {
				_m.AddressZip = value.String
			}
		case pharmacy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pharmacy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Pharmacy.
// This includes values selected through modifiers, order, etc.
func (_m *Pharmacy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOffers queries the "offers" edge of the Pharmacy entity.
func (_m *Pharmacy) QueryOffers() *OfferQuery {
	return NewPharmacyClient(_m.config).QueryOffers(_m)
}

// Update returns a builder for updating this Pharmacy.
// Note that you need to call Pharmacy.Unwrap() before calling this method if this Pharmacy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Pharmacy) Update() *PharmacyUpdateOne {
	return NewPharmacyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Pharmacy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Pharmacy) Unwrap() *Pharmacy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Pharmacy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Pharmacy) String() string {
	var builder strings.Builder
	builder.WriteString("Pharmacy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("contact_phone=")
	builder.WriteString(_m.ContactPhone)
	builder.WriteString(", ")
	builder.WriteString("npi=")
	builder.WriteString(_m.Npi)
	builder.WriteString(", ")
	builder.WriteString("dea=")
	builder.WriteString(_m.Dea)
	builder.WriteString(", ")
	builder.WriteString("ncpdp=")
	builder.WriteString(_m.Ncpdp)
	builder.WriteString(", ")
	builder.WriteString("address_street1=")
	builder.WriteString(_m.AddressStreet1)
	builder.WriteString(", ")
	builder.WriteString("address_street2=")
	builder.WriteString(_m.AddressStreet2)
	builder.WriteString(", ")
	builder.WriteString("address_city=")
	builder.WriteString(_m.AddressCity)
	builder.WriteString(", ")
	builder.WriteString("address_state=")
	builder.WriteString(_m.AddressState)
	builder.WriteString(", ")
	builder.WriteString("address_zip=")
	builder.WriteString(_m.AddressZip)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Pharmacies is a parsable slice of Pharmacy.
type Pharmacies []*Pharmacy
