// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LoneWolfPR/MedMarket/backend/ent/pharmacy"
	"github.com/google/uuid"
)

// PharmacyCreate is the builder for creating a Pharmacy entity.
type PharmacyCreate struct {
	config
	mutation *PharmacyMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *PharmacyCreate) SetName(v string) *PharmacyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetContactPhone sets the "contact_phone" field.
func (_c *PharmacyCreate) SetContactPhone(v string) *PharmacyCreate {
	_c.mutation.SetContactPhone(v)
	return _c
}

// SetNpi sets the "npi" field.
func (_c *PharmacyCreate) SetNpi(v string) *PharmacyCreate {
	_c.mutation.SetNpi(v)
	return _c
}

// SetDea sets the "dea" field.
func (_c *PharmacyCreate) SetDea(v string) *PharmacyCreate {
	_c.mutation.SetDea(v)
	return _c
}

// SetNcpdp sets the "ncpdp" field.
func (_c *PharmacyCreate) SetNcpdp(v string) *PharmacyCreate {
	_c.mutation.SetNcpdp(v)
	return _c
}

// SetAddressStreet1 sets the "address_street1" field.
func (_c *PharmacyCreate) SetAddressStreet1(v string) *PharmacyCreate {
	_c.mutation.SetAddressStreet1(v)
	return _c
}

// SetAddressStreet2 sets the "address_street2" field.
func (_c *PharmacyCreate) SetAddressStreet2(v string) *PharmacyCreate {
	_c.mutation.SetAddressStreet2(v)
	return _c
}

// SetNillableAddressStreet2 sets the "address_street2" field if the given value is not nil.
func (_c *PharmacyCreate) SetNillableAddressStreet2(v *string) *PharmacyCreate {
	if v != nil {
		_c.SetAddressStreet2(*v)
	}
	return _c
}

// SetAddressCity sets the "address_city" field.
func (_c *PharmacyCreate) SetAddressCity(v string) *PharmacyCreate {
	_c.mutation.SetAddressCity(v)
	return _c
}

// SetAddressState sets the "address_state" field.
func (_c *PharmacyCreate) SetAddressState(v string) *PharmacyCreate {
	_c.mutation.SetAddressState(v)
	return _c
}

// SetAddressZip sets the "address_zip" field.
func (_c *PharmacyCreate) SetAddressZip(v string) *PharmacyCreate {
	_c.mutation.SetAddressZip(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PharmacyCreate) SetCreatedAt(v time.Time) *PharmacyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PharmacyCreate) SetNillableCreatedAt(v *time.Time) *PharmacyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PharmacyCreate) SetUpdatedAt(v time.Time) *PharmacyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PharmacyCreate) SetNillableUpdatedAt(v *time.Time) *PharmacyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PharmacyCreate) SetID(v uuid.UUID) *PharmacyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PharmacyCreate) SetNillableID(v *uuid.UUID) *PharmacyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PharmacyMutation object of the builder.
func (_c *PharmacyCreate) Mutation() *PharmacyMutation {
	return _c.mutation
}

// Save creates the Pharmacy in the database.
func (_c *PharmacyCreate) Save(ctx context.Context) (*Pharmacy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PharmacyCreate) SaveX(ctx context.Context) *Pharmacy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PharmacyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PharmacyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PharmacyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pharmacy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := pharmacy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := pharmacy.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PharmacyCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Pharmacy.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := pharmacy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Pharmacy.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContactPhone(); !ok {
		return &ValidationError{Name: "contact_phone", err: errors.New(`ent: missing required field "Pharmacy.contact_phone"`)}
	}
	if v, ok := _c.mutation.ContactPhone(); ok {
		if err := pharmacy.ContactPhoneValidator(v); err != nil {
			return &ValidationError{Name: "contact_phone", err: fmt.Errorf(`ent: validator failed for field "Pharmacy.contact_phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Npi(); !ok {
		return &ValidationError{Name: "npi", err: errors.New(`ent: missing required field "Pharmacy.npi"`)}
	}
	if v, ok := _c.mutation.Npi(); ok {
		if err := pharmacy.NpiValidator(v); err != nil {
			return &ValidationError{Name: "npi", err: fmt.Errorf(`ent: validator failed for field "Pharmacy.npi": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Dea(); !ok {
		return &ValidationError{Name: "dea", err: errors.New(`ent: missing required field "Pharmacy.dea"`)}
	}
	if v, ok := _c.mutation.Dea(); ok {
		if err := pharmacy.DeaValidator(v); err != nil {
			return &ValidationError{Name: "dea", err: fmt.Errorf(`ent: validator failed for field "Pharmacy.dea": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Ncpdp(); !ok {
		return &ValidationError{Name: "ncpdp", err: errors.New(`ent: missing required field "Pharmacy.ncpdp"`)}
	}
	if v, ok := _c.mutation.Ncpdp(); ok {
		if err := pharmacy.NcpdpValidator(v); err != nil {
			return &ValidationError{Name: "ncpdp", err: fmt.Errorf(`ent: validator failed for field "Pharmacy.ncpdp": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AddressStreet1(); !ok {
		return &ValidationError{Name: "address_street1", err: errors.New(`ent: missing required field "Pharmacy.address_street1"`)}
	}
	if v, ok := _c.mutation.AddressStreet1(); ok {
		if err := pharmacy.AddressStreet1Validator(v); err != nil {
			return &ValidationError{Name: "address_street1", err: fmt.Errorf(`ent: validator failed for field "Pharmacy.address_street1": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AddressCity(); !ok {
		return &ValidationError{Name: "address_city", err: errors.New(`ent: missing required field "Pharmacy.address_city"`)}
	}
	if v, ok := _c.mutation.AddressCity(); ok {
		if err := pharmacy.AddressCityValidator(v); err != nil {
			return &ValidationError{Name: "address_city", err: fmt.Errorf(`ent: validator failed for field "Pharmacy.address_city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AddressState(); !ok {
		return &ValidationError{Name: "address_state", err: errors.New(`ent: missing required field "Pharmacy.address_state"`)}
	}
	if v, ok := _c.mutation.AddressState(); ok {
		if err := pharmacy.AddressStateValidator(v); err != nil {
			return &ValidationError{Name: "address_state", err: fmt.Errorf(`ent: validator failed for field "Pharmacy.address_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AddressZip(); !ok {
		return &ValidationError{Name: "address_zip", err: errors.New(`ent: missing required field "Pharmacy.address_zip"`)}
	}
	if v, ok := _c.mutation.AddressZip(); ok {
		if err := pharmacy.AddressZipValidator(v); err != nil {
			return &ValidationError{Name: "address_zip", err: fmt.Errorf(`ent: validator failed for field "Pharmacy.address_zip": %w`, err)}
		}
	}
	return nil
}

func (_c *PharmacyCreate) sqlSave(ctx context.Context) (*Pharmacy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PharmacyCreate) createSpec() (*Pharmacy, *sqlgraph.CreateSpec) {
	var (
		_node = &Pharmacy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pharmacy.Table, sqlgraph.NewFieldSpec(pharmacy.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(pharmacy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ContactPhone(); ok {
		_spec.SetField(pharmacy.FieldContactPhone, field.TypeString, value)
		_node.ContactPhone = value
	}
	if value, ok := _c.mutation.Npi(); ok {
		_spec.SetField(pharmacy.FieldNpi, field.TypeString, value)
		_node.Npi = value
	}
	if value, ok := _c.mutation.Dea(); ok {
		_spec.SetField(pharmacy.FieldDea, field.TypeString, value)
		_node.Dea = value
	}
	if value, ok := _c.mutation.Ncpdp(); ok {
		_spec.SetField(pharmacy.FieldNcpdp, field.TypeString, value)
		_node.Ncpdp = value
	}
	if value, ok := _c.mutation.AddressStreet1(); ok {
		_spec.SetField(pharmacy.FieldAddressStreet1, field.TypeString, value)
		_node.AddressStreet1 = value
	}
	if value, ok := _c.mutation.AddressStreet2(); ok {
		_spec.SetField(pharmacy.FieldAddressStreet2, field.TypeString, value)
		_node.AddressStreet2 = value
	}
	if value, ok := _c.mutation.AddressCity(); ok {
		_spec.SetField(pharmacy.FieldAddressCity, field.TypeString, value)
		_node.AddressCity = value
	}
	if value, ok := _c.mutation.AddressState(); ok {
		_spec.SetField(pharmacy.FieldAddressState, field.TypeString, value)
		_node.AddressState = value
	}
	if value, ok := _c.mutation.AddressZip(); ok {
		_spec.SetField(pharmacy.FieldAddressZip, field.TypeString, value)
		_node.AddressZip = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pharmacy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pharmacy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PharmacyCreateBulk is the builder for creating many Pharmacy entities in bulk.
type PharmacyCreateBulk struct {
	config
	err      error
	builders []*PharmacyCreate
}

// Save creates the Pharmacy entities in the database.
func (_c *PharmacyCreateBulk) Save(ctx context.Context) ([]*Pharmacy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Pharmacy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PharmacyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PharmacyCreateBulk) SaveX(ctx context.Context) []*Pharmacy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PharmacyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PharmacyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
