// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LoneWolfPR/MedMarket/backend/ent/pharmacy"
	"github.com/LoneWolfPR/MedMarket/backend/ent/predicate"
)

// PharmacyDelete is the builder for deleting a Pharmacy entity.
type PharmacyDelete struct {
	config
	hooks    []Hook
	mutation *PharmacyMutation
}

// Where appends a list predicates to the PharmacyDelete builder.
func (_d *PharmacyDelete) Where(ps ...predicate.Pharmacy) *PharmacyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PharmacyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PharmacyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PharmacyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pharmacy.Table, sqlgraph.NewFieldSpec(pharmacy.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PharmacyDeleteOne is the builder for deleting a single Pharmacy entity.
type PharmacyDeleteOne struct {
	_d *PharmacyDelete
}

// Where appends a list predicates to the PharmacyDelete builder.
func (_d *PharmacyDeleteOne) Where(ps ...predicate.Pharmacy) *PharmacyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PharmacyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pharmacy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PharmacyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
