// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LoneWolfPR/MedMarket/backend/ent/offer"
	"github.com/LoneWolfPR/MedMarket/backend/ent/prescription"
	"github.com/LoneWolfPR/MedMarket/backend/ent/user"
	"github.com/google/uuid"
)

// PrescriptionCreate is the builder for creating a Prescription entity.
type PrescriptionCreate struct {
	config
	mutation *PrescriptionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *PrescriptionCreate) SetUserID(v uuid.UUID) *PrescriptionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetDocumentKey sets the "document_key" field.
func (_c *PrescriptionCreate) SetDocumentKey(v string) *PrescriptionCreate {
	_c.mutation.SetDocumentKey(v)
	return _c
}

// SetPhysicianName sets the "physician_name" field.
func (_c *PrescriptionCreate) SetPhysicianName(v string) *PrescriptionCreate {
	_c.mutation.SetPhysicianName(v)
	return _c
}

// SetMedName sets the "med_name" field.
func (_c *PrescriptionCreate) SetMedName(v string) *PrescriptionCreate {
	_c.mutation.SetMedName(v)
	return _c
}

// SetMedStrengthValue sets the "med_strength_value" field.
func (_c *PrescriptionCreate) SetMedStrengthValue(v string) *PrescriptionCreate {
	_c.mutation.SetMedStrengthValue(v)
	return _c
}

// SetMedStrengthUnit sets the "med_strength_unit" field.
func (_c *PrescriptionCreate) SetMedStrengthUnit(v string) *PrescriptionCreate {
	_c.mutation.SetMedStrengthUnit(v)
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *PrescriptionCreate) SetQuantity(v int) *PrescriptionCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PrescriptionCreate) SetCreatedAt(v time.Time) *PrescriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PrescriptionCreate) SetNillableCreatedAt(v *time.Time) *PrescriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PrescriptionCreate) SetUpdatedAt(v time.Time) *PrescriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PrescriptionCreate) SetNillableUpdatedAt(v *time.Time) *PrescriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PrescriptionCreate) SetID(v uuid.UUID) *PrescriptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PrescriptionCreate) SetNillableID(v *uuid.UUID) *PrescriptionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *PrescriptionCreate) SetOwnerID(id uuid.UUID) *PrescriptionCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *PrescriptionCreate) SetOwner(v *User) *PrescriptionCreate {
	return _c.SetOwnerID(v.ID)
}

// AddOfferIDs adds the "offers" edge to the Offer entity by IDs.
func (_c *PrescriptionCreate) AddOfferIDs(ids ...uuid.UUID) *PrescriptionCreate {
	_c.mutation.AddOfferIDs(ids...)
	return _c
}

// AddOffers adds the "offers" edges to the Offer entity.
func (_c *PrescriptionCreate) AddOffers(v ...*Offer) *PrescriptionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOfferIDs(ids...)
}

// Mutation returns the PrescriptionMutation object of the builder.
func (_c *PrescriptionCreate) Mutation() *PrescriptionMutation {
	return _c.mutation
}

// Save creates the Prescription in the database.
func (_c *PrescriptionCreate) Save(ctx context.Context) (*Prescription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PrescriptionCreate) SaveX(ctx context.Context) *Prescription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PrescriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PrescriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PrescriptionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := prescription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := prescription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := prescription.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PrescriptionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Prescription.user_id"`)}
	}
	if _, ok := _c.mutation.DocumentKey(); !ok {
		return &ValidationError{Name: "document_key", err: errors.New(`ent: missing required field "Prescription.document_key"`)}
	}
	if v, ok := _c.mutation.DocumentKey(); ok {
		if err := prescription.DocumentKeyValidator(v); err != nil {
			return &ValidationError{Name: "document_key", err: fmt.Errorf(`ent: validator failed for field "Prescription.document_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PhysicianName(); !ok {
		return &ValidationError{Name: "physician_name", err: errors.New(`ent: missing required field "Prescription.physician_name"`)}
	}
	if v, ok := _c.mutation.PhysicianName(); ok {
		if err := prescription.PhysicianNameValidator(v); err != nil {
			return &ValidationError{Name: "physician_name", err: fmt.Errorf(`ent: validator failed for field "Prescription.physician_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MedName(); !ok {
		return &ValidationError{Name: "med_name", err: errors.New(`ent: missing required field "Prescription.med_name"`)}
	}
	if v, ok := _c.mutation.MedName(); ok {
		if err := prescription.MedNameValidator(v); err != nil {
			return &ValidationError{Name: "med_name", err: fmt.Errorf(`ent: validator failed for field "Prescription.med_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MedStrengthValue(); !ok {
		return &ValidationError{Name: "med_strength_value", err: errors.New(`ent: missing required field "Prescription.med_strength_value"`)}
	}
	if v, ok := _c.mutation.MedStrengthValue(); ok {
		if err := prescription.MedStrengthValueValidator(v); err != nil {
			return &ValidationError{Name: "med_strength_value", err: fmt.Errorf(`ent: validator failed for field "Prescription.med_strength_value": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MedStrengthUnit(); !ok {
		return &ValidationError{Name: "med_strength_unit", err: errors.New(`ent: missing required field "Prescription.med_strength_unit"`)}
	}
	if v, ok := _c.mutation.MedStrengthUnit(); ok {
		if err := prescription.MedStrengthUnitValidator(v); err != nil {
			return &ValidationError{Name: "med_strength_unit", err: fmt.Errorf(`ent: validator failed for field "Prescription.med_strength_unit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Prescription.quantity"`)}
	}
	if v, ok := _c.mutation.Quantity(); ok {
		if err := prescription.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Prescription.quantity": %w`, err)}
		}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Prescription.owner"`)}
	}
	return nil
}

func (_c *PrescriptionCreate) sqlSave(ctx context.Context) (*Prescription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PrescriptionCreate) createSpec() (*Prescription, *sqlgraph.CreateSpec) {
	var (
		_node = &Prescription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(prescription.Table, sqlgraph.NewFieldSpec(prescription.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DocumentKey(); ok {
		_spec.SetField(prescription.FieldDocumentKey, field.TypeString, value)
		_node.DocumentKey = value
	}
	if value, ok := _c.mutation.PhysicianName(); ok {
		_spec.SetField(prescription.FieldPhysicianName, field.TypeString, value)
		_node.PhysicianName = value
	}
	if value, ok := _c.mutation.MedName(); ok {
		_spec.SetField(prescription.FieldMedName, field.TypeString, value)
		_node.MedName = value
	}
	if value, ok := _c.mutation.MedStrengthValue(); ok {
		_spec.SetField(prescription.FieldMedStrengthValue, field.TypeString, value)
		_node.MedStrengthValue = value
	}
	if value, ok := _c.mutation.MedStrengthUnit(); ok {
		_spec.SetField(prescription.FieldMedStrengthUnit, field.TypeString, value)
		_node.MedStrengthUnit = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(prescription.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(prescription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(prescription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   prescription.OwnerTable,
			Columns: []string{prescription.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OffersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prescription.OffersTable,
			Columns: []string{prescription.OffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(offer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PrescriptionCreateBulk is the builder for creating many Prescription entities in bulk.
type PrescriptionCreateBulk struct {
	config
	err      error
	builders []*PrescriptionCreate
}

// Save creates the Prescription entities in the database.
func (_c *PrescriptionCreateBulk) Save(ctx context.Context) ([]*Prescription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Prescription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PrescriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PrescriptionCreateBulk) SaveX(ctx context.Context) []*Prescription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PrescriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PrescriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
