// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LoneWolfPR/MedMarket/backend/ent/offer"
	"github.com/LoneWolfPR/MedMarket/backend/ent/predicate"
	"github.com/LoneWolfPR/MedMarket/backend/ent/prescription"
	"github.com/google/uuid"
)

// PrescriptionUpdate is the builder for updating Prescription entities.
type PrescriptionUpdate struct {
	config
	hooks    []Hook
	mutation *PrescriptionMutation
}

// Where appends a list predicates to the PrescriptionUpdate builder.
func (_u *PrescriptionUpdate) Where(ps ...predicate.Prescription) *PrescriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPhysicianName sets the "physician_name" field.
func (_u *PrescriptionUpdate) SetPhysicianName(v string) *PrescriptionUpdate {
	_u.mutation.SetPhysicianName(v)
	return _u
}

// SetNillablePhysicianName sets the "physician_name" field if the given value is not nil.
func (_u *PrescriptionUpdate) SetNillablePhysicianName(v *string) *PrescriptionUpdate {
	if v != nil {
		_u.SetPhysicianName(*v)
	}
	return _u
}

// SetMedName sets the "med_name" field.
func (_u *PrescriptionUpdate) SetMedName(v string) *PrescriptionUpdate {
	_u.mutation.SetMedName(v)
	return _u
}

// SetNillableMedName sets the "med_name" field if the given value is not nil.
func (_u *PrescriptionUpdate) SetNillableMedName(v *string) *PrescriptionUpdate {
	if v != nil {
		_u.SetMedName(*v)
	}
	return _u
}

// SetMedStrengthValue sets the "med_strength_value" field.
func (_u *PrescriptionUpdate) SetMedStrengthValue(v string) *PrescriptionUpdate {
	_u.mutation.SetMedStrengthValue(v)
	return _u
}

// SetNillableMedStrengthValue sets the "med_strength_value" field if the given value is not nil.
func (_u *PrescriptionUpdate) SetNillableMedStrengthValue(v *string) *PrescriptionUpdate {
	if v != nil {
		_u.SetMedStrengthValue(*v)
	}
	return _u
}

// SetMedStrengthUnit sets the "med_strength_unit" field.
func (_u *PrescriptionUpdate) SetMedStrengthUnit(v string) *PrescriptionUpdate {
	_u.mutation.SetMedStrengthUnit(v)
	return _u
}

// SetNillableMedStrengthUnit sets the "med_strength_unit" field if the given value is not nil.
func (_u *PrescriptionUpdate) SetNillableMedStrengthUnit(v *string) *PrescriptionUpdate {
	if v != nil {
		_u.SetMedStrengthUnit(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *PrescriptionUpdate) SetQuantity(v int) *PrescriptionUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *PrescriptionUpdate) SetNillableQuantity(v *int) *PrescriptionUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *PrescriptionUpdate) AddQuantity(v int) *PrescriptionUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PrescriptionUpdate) SetUpdatedAt(v time.Time) *PrescriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddOfferIDs adds the "offers" edge to the Offer entity by IDs.
func (_u *PrescriptionUpdate) AddOfferIDs(ids ...uuid.UUID) *PrescriptionUpdate {
	_u.mutation.AddOfferIDs(ids...)
	return _u
}

// AddOffers adds the "offers" edges to the Offer entity.
func (_u *PrescriptionUpdate) AddOffers(v ...*Offer) *PrescriptionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOfferIDs(ids...)
}

// Mutation returns the PrescriptionMutation object of the builder.
func (_u *PrescriptionUpdate) Mutation() *PrescriptionMutation {
	return _u.mutation
}

// ClearOffers clears all "offers" edges to the Offer entity.
func (_u *PrescriptionUpdate) ClearOffers() *PrescriptionUpdate {
	_u.mutation.ClearOffers()
	return _u
}

// RemoveOfferIDs removes the "offers" edge to Offer entities by IDs.
func (_u *PrescriptionUpdate) RemoveOfferIDs(ids ...uuid.UUID) *PrescriptionUpdate {
	_u.mutation.RemoveOfferIDs(ids...)
	return _u
}

// RemoveOffers removes "offers" edges to Offer entities.
func (_u *PrescriptionUpdate) RemoveOffers(v ...*Offer) *PrescriptionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOfferIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PrescriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PrescriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PrescriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PrescriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PrescriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := prescription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PrescriptionUpdate) check() error {
	if v, ok := _u.mutation.PhysicianName(); ok {
		if err := prescription.PhysicianNameValidator(v); err != nil {
			return &ValidationError{Name: "physician_name", err: fmt.Errorf(`ent: validator failed for field "Prescription.physician_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MedName(); ok {
		if err := prescription.MedNameValidator(v); err != nil {
			return &ValidationError{Name: "med_name", err: fmt.Errorf(`ent: validator failed for field "Prescription.med_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MedStrengthValue(); ok {
		if err := prescription.MedStrengthValueValidator(v); err != nil {
			return &ValidationError{Name: "med_strength_value", err: fmt.Errorf(`ent: validator failed for field "Prescription.med_strength_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MedStrengthUnit(); ok {
		if err := prescription.MedStrengthUnitValidator(v); err != nil {
			return &ValidationError{Name: "med_strength_unit", err: fmt.Errorf(`ent: validator failed for field "Prescription.med_strength_unit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quantity(); ok {
		if err := prescription.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Prescription.quantity": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Prescription.owner"`)
	}
	return nil
}

func (_u *PrescriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(prescription.Table, prescription.Columns, sqlgraph.NewFieldSpec(prescription.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PhysicianName(); ok {
		_spec.SetField(prescription.FieldPhysicianName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MedName(); ok {
		_spec.SetField(prescription.FieldMedName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MedStrengthValue(); ok {
		_spec.SetField(prescription.FieldMedStrengthValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.MedStrengthUnit(); ok {
		_spec.SetField(prescription.FieldMedStrengthUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(prescription.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(prescription.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(prescription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OffersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prescription.OffersTable,
			Columns: []string{prescription.OffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(offer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOffersIDs(); len(nodes) > 0 && !_u.mutation.OffersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prescription.OffersTable,
			Columns: []string{prescription.OffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(offer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OffersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prescription.OffersTable,
			Columns: []string{prescription.OffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(offer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prescription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PrescriptionUpdateOne is the builder for updating a single Prescription entity.
type PrescriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PrescriptionMutation
}

// SetPhysicianName sets the "physician_name" field.
func (_u *PrescriptionUpdateOne) SetPhysicianName(v string) *PrescriptionUpdateOne {
	_u.mutation.SetPhysicianName(v)
	return _u
}

// SetNillablePhysicianName sets the "physician_name" field if the given value is not nil.
func (_u *PrescriptionUpdateOne) SetNillablePhysicianName(v *string) *PrescriptionUpdateOne {
	if v != nil {
		_u.SetPhysicianName(*v)
	}
	return _u
}

// SetMedName sets the "med_name" field.
func (_u *PrescriptionUpdateOne) SetMedName(v string) *PrescriptionUpdateOne {
	_u.mutation.SetMedName(v)
	return _u
}

// SetNillableMedName sets the "med_name" field if the given value is not nil.
func (_u *PrescriptionUpdateOne) SetNillableMedName(v *string) *PrescriptionUpdateOne {
	if v != nil {
		_u.SetMedName(*v)
	}
	return _u
}

// SetMedStrengthValue sets the "med_strength_value" field.
func (_u *PrescriptionUpdateOne) SetMedStrengthValue(v string) *PrescriptionUpdateOne {
	_u.mutation.SetMedStrengthValue(v)
	return _u
}

// SetNillableMedStrengthValue sets the "med_strength_value" field if the given value is not nil.
func (_u *PrescriptionUpdateOne) SetNillableMedStrengthValue(v *string) *PrescriptionUpdateOne {
	if v != nil {
		_u.SetMedStrengthValue(*v)
	}
	return _u
}

// SetMedStrengthUnit sets the "med_strength_unit" field.
func (_u *PrescriptionUpdateOne) SetMedStrengthUnit(v string) *PrescriptionUpdateOne {
	_u.mutation.SetMedStrengthUnit(v)
	return _u
}

// SetNillableMedStrengthUnit sets the "med_strength_unit" field if the given value is not nil.
func (_u *PrescriptionUpdateOne) SetNillableMedStrengthUnit(v *string) *PrescriptionUpdateOne {
	if v != nil {
		_u.SetMedStrengthUnit(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *PrescriptionUpdateOne) SetQuantity(v int) *PrescriptionUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *PrescriptionUpdateOne) SetNillableQuantity(v *int) *PrescriptionUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *PrescriptionUpdateOne) AddQuantity(v int) *PrescriptionUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PrescriptionUpdateOne) SetUpdatedAt(v time.Time) *PrescriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddOfferIDs adds the "offers" edge to the Offer entity by IDs.
func (_u *PrescriptionUpdateOne) AddOfferIDs(ids ...uuid.UUID) *PrescriptionUpdateOne {
	_u.mutation.AddOfferIDs(ids...)
	return _u
}

// AddOffers adds the "offers" edges to the Offer entity.
func (_u *PrescriptionUpdateOne) AddOffers(v ...*Offer) *PrescriptionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOfferIDs(ids...)
}

// Mutation returns the PrescriptionMutation object of the builder.
func (_u *PrescriptionUpdateOne) Mutation() *PrescriptionMutation {
	return _u.mutation
}

// ClearOffers clears all "offers" edges to the Offer entity.
func (_u *PrescriptionUpdateOne) ClearOffers() *PrescriptionUpdateOne {
	_u.mutation.ClearOffers()
	return _u
}

// RemoveOfferIDs removes the "offers" edge to Offer entities by IDs.
func (_u *PrescriptionUpdateOne) RemoveOfferIDs(ids ...uuid.UUID) *PrescriptionUpdateOne {
	_u.mutation.RemoveOfferIDs(ids...)
	return _u
}

// RemoveOffers removes "offers" edges to Offer entities.
func (_u *PrescriptionUpdateOne) RemoveOffers(v ...*Offer) *PrescriptionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOfferIDs(ids...)
}

// Where appends a list predicates to the PrescriptionUpdate builder.
func (_u *PrescriptionUpdateOne) Where(ps ...predicate.Prescription) *PrescriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PrescriptionUpdateOne) Select(field string, fields ...string) *PrescriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Prescription entity.
func (_u *PrescriptionUpdateOne) Save(ctx context.Context) (*Prescription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PrescriptionUpdateOne) SaveX(ctx context.Context) *Prescription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PrescriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PrescriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PrescriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := prescription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PrescriptionUpdateOne) check() error {
	if v, ok := _u.mutation.PhysicianName(); ok {
		if err := prescription.PhysicianNameValidator(v); err != nil {
			return &ValidationError{Name: "physician_name", err: fmt.Errorf(`ent: validator failed for field "Prescription.physician_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MedName(); ok {
		if err := prescription.MedNameValidator(v); err != nil {
			return &ValidationError{Name: "med_name", err: fmt.Errorf(`ent: validator failed for field "Prescription.med_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MedStrengthValue(); ok {
		if err := prescription.MedStrengthValueValidator(v); err != nil {
			return &ValidationError{Name: "med_strength_value", err: fmt.Errorf(`ent: validator failed for field "Prescription.med_strength_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MedStrengthUnit(); ok {
		if err := prescription.MedStrengthUnitValidator(v); err != nil {
			return &ValidationError{Name: "med_strength_unit", err: fmt.Errorf(`ent: validator failed for field "Prescription.med_strength_unit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quantity(); ok {
		if err := prescription.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Prescription.quantity": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Prescription.owner"`)
	}
	return nil
}

func (_u *PrescriptionUpdateOne) sqlSave(ctx context.Context) (_node *Prescription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(prescription.Table, prescription.Columns, sqlgraph.NewFieldSpec(prescription.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Prescription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prescription.FieldID)
		for _, f := range fields {
			if !prescription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != prescription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PhysicianName(); ok {
		_spec.SetField(prescription.FieldPhysicianName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MedName(); ok {
		_spec.SetField(prescription.FieldMedName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MedStrengthValue(); ok {
		_spec.SetField(prescription.FieldMedStrengthValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.MedStrengthUnit(); ok {
		_spec.SetField(prescription.FieldMedStrengthUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(prescription.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(prescription.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(prescription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OffersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prescription.OffersTable,
			Columns: []string{prescription.OffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(offer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOffersIDs(); len(nodes) > 0 && !_u.mutation.OffersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prescription.OffersTable,
			Columns: []string{prescription.OffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(offer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OffersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prescription.OffersTable,
			Columns: []string{prescription.OffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(offer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Prescription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prescription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
