// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/LoneWolfPR/MedMarket/backend/ent/offer"
	"github.com/LoneWolfPR/MedMarket/backend/ent/pharmacy"
	"github.com/LoneWolfPR/MedMarket/backend/ent/prescription"
	"github.com/LoneWolfPR/MedMarket/backend/ent/schema"
	"github.com/LoneWolfPR/MedMarket/backend/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	offerFields := schema.Offer{}.Fields()
	_ = offerFields
	// offerDescPriceCents is the schema descriptor for price_cents field.
	offerDescPriceCents := offerFields[2].Descriptor()
	// offer.PriceCentsValidator is a validator for the "price_cents" field. It is called by the builders before save.
	offer.PriceCentsValidator = offerDescPriceCents.Validators[0].(func(int64) error)
	// offerDescPharmacyItemID is the schema descriptor for pharmacy_item_id field.
	offerDescPharmacyItemID := offerFields[4].Descriptor()
	// offer.PharmacyItemIDValidator is a validator for the "pharmacy_item_id" field. It is called by the builders before save.
	offer.PharmacyItemIDValidator = offerDescPharmacyItemID.Validators[0].(func(string) error)
	// offerDescCreatedAt is the schema descriptor for created_at field.
	offerDescCreatedAt := offerFields[6].Descriptor()
	// offer.DefaultCreatedAt holds the default value on creation for the created_at field.
	offer.DefaultCreatedAt = offerDescCreatedAt.Default.(func() time.Time)
	// offerDescUpdatedAt is the schema descriptor for updated_at field.
	offerDescUpdatedAt := offerFields[7].Descriptor()
	// offer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	offer.DefaultUpdatedAt = offerDescUpdatedAt.Default.(func() time.Time)
	// offer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	offer.UpdateDefaultUpdatedAt = offerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// offerDescID is the schema descriptor for id field.
	offerDescID := offerFields[0].Descriptor()
	// offer.DefaultID holds the default value on creation for the id field.
	offer.DefaultID = offerDescID.Default.(func() uuid.UUID)
	pharmacyFields := schema.Pharmacy{}.Fields()
	_ = pharmacyFields
	// pharmacyDescCode is the schema descriptor for code field.
	pharmacyDescCode := pharmacyFields[1].Descriptor()
	// pharmacy.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	pharmacy.CodeValidator = pharmacyDescCode.Validators[0].(func(string) error)
	// pharmacyDescName is the schema descriptor for name field.
	pharmacyDescName := pharmacyFields[2].Descriptor()
	// pharmacy.NameValidator is a validator for the "name" field. It is called by the builders before save.
	pharmacy.NameValidator = pharmacyDescName.Validators[0].(func(string) error)
	// pharmacyDescContactPhone is the schema descriptor for contact_phone field.
	pharmacyDescContactPhone := pharmacyFields[3].Descriptor()
	// pharmacy.ContactPhoneValidator is a validator for the "contact_phone" field. It is called by the builders before save.
	pharmacy.ContactPhoneValidator = pharmacyDescContactPhone.Validators[0].(func(string) error)
	// pharmacyDescNpi is the schema descriptor for npi field.
	pharmacyDescNpi := pharmacyFields[4].Descriptor()
	// pharmacy.NpiValidator is a validator for the "npi" field. It is called by the builders before save.
	pharmacy.NpiValidator = pharmacyDescNpi.Validators[0].(func(string) error)
	// pharmacyDescDea is the schema descriptor for dea field.
	pharmacyDescDea := pharmacyFields[5].Descriptor()
	// pharmacy.DeaValidator is a validator for the "dea" field. It is called by the builders before save.
	pharmacy.DeaValidator = pharmacyDescDea.Validators[0].(func(string) error)
	// pharmacyDescNcpdp is the schema descriptor for ncpdp field.
	pharmacyDescNcpdp := pharmacyFields[6].Descriptor()
	// pharmacy.NcpdpValidator is a validator for the "ncpdp" field. It is called by the builders before save.
	pharmacy.NcpdpValidator = pharmacyDescNcpdp.Validators[0].(func(string) error)
	// pharmacyDescAddressStreet1 is the schema descriptor for address_street1 field.
	pharmacyDescAddressStreet1 := pharmacyFields[7].Descriptor()
	// pharmacy.AddressStreet1Validator is a validator for the "address_street1" field. It is called by the builders before save.
	pharmacy.AddressStreet1Validator = pharmacyDescAddressStreet1.Validators[0].(func(string) error)
	// pharmacyDescAddressCity is the schema descriptor for address_city field.
	pharmacyDescAddressCity := pharmacyFields[9].Descriptor()
	// pharmacy.AddressCityValidator is a validator for the "address_city" field. It is called by the builders before save.
	pharmacy.AddressCityValidator = pharmacyDescAddressCity.Validators[0].(func(string) error)
	// pharmacyDescAddressState is the schema descriptor for address_state field.
	pharmacyDescAddressState := pharmacyFields[10].Descriptor()
	// pharmacy.AddressStateValidator is a validator for the "address_state" field. It is called by the builders before save.
	pharmacy.AddressStateValidator = pharmacyDescAddressState.Validators[0].(func(string) error)
	// pharmacyDescAddressZip is the schema descriptor for address_zip field.
	pharmacyDescAddressZip := pharmacyFields[11].Descriptor()
	// pharmacy.AddressZipValidator is a validator for the "address_zip" field. It is called by the builders before save.
	pharmacy.AddressZipValidator = pharmacyDescAddressZip.Validators[0].(func(string) error)
	// pharmacyDescCreatedAt is the schema descriptor for created_at field.
	pharmacyDescCreatedAt := pharmacyFields[12].Descriptor()
	// pharmacy.DefaultCreatedAt holds the default value on creation for the created_at field.
	pharmacy.DefaultCreatedAt = pharmacyDescCreatedAt.Default.(func() time.Time)
	// pharmacyDescUpdatedAt is the schema descriptor for updated_at field.
	pharmacyDescUpdatedAt := pharmacyFields[13].Descriptor()
	// pharmacy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pharmacy.DefaultUpdatedAt = pharmacyDescUpdatedAt.Default.(func() time.Time)
	// pharmacy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pharmacy.UpdateDefaultUpdatedAt = pharmacyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// pharmacyDescID is the schema descriptor for id field.
	pharmacyDescID := pharmacyFields[0].Descriptor()
	// pharmacy.DefaultID holds the default value on creation for the id field.
	pharmacy.DefaultID = pharmacyDescID.Default.(func() uuid.UUID)
	prescriptionFields := schema.Prescription{}.Fields()
	_ = prescriptionFields
	// prescriptionDescDocumentKey is the schema descriptor for document_key field.
	prescriptionDescDocumentKey := prescriptionFields[2].Descriptor()
	// prescription.DocumentKeyValidator is a validator for the "document_key" field. It is called by the builders before save.
	prescription.DocumentKeyValidator = prescriptionDescDocumentKey.Validators[0].(func(string) error)
	// prescriptionDescPhysicianName is the schema descriptor for physician_name field.
	prescriptionDescPhysicianName := prescriptionFields[3].Descriptor()
	// prescription.PhysicianNameValidator is a validator for the "physician_name" field. It is called by the builders before save.
	prescription.PhysicianNameValidator = prescriptionDescPhysicianName.Validators[0].(func(string) error)
	// prescriptionDescMedName is the schema descriptor for med_name field.
	prescriptionDescMedName := prescriptionFields[4].Descriptor()
	// prescription.MedNameValidator is a validator for the "med_name" field. It is called by the builders before save.
	prescription.MedNameValidator = prescriptionDescMedName.Validators[0].(func(string) error)
	// prescriptionDescMedStrengthValue is the schema descriptor for med_strength_value field.
	prescriptionDescMedStrengthValue := prescriptionFields[5].Descriptor()
	// prescription.MedStrengthValueValidator is a validator for the "med_strength_value" field. It is called by the builders before save.
	prescription.MedStrengthValueValidator = prescriptionDescMedStrengthValue.Validators[0].(func(string) error)
	// prescriptionDescMedStrengthUnit is the schema descriptor for med_strength_unit field.
	prescriptionDescMedStrengthUnit := prescriptionFields[6].Descriptor()
	// prescription.MedStrengthUnitValidator is a validator for the "med_strength_unit" field. It is called by the builders before save.
	prescription.MedStrengthUnitValidator = prescriptionDescMedStrengthUnit.Validators[0].(func(string) error)
	// prescriptionDescQuantity is the schema descriptor for quantity field.
	prescriptionDescQuantity := prescriptionFields[7].Descriptor()
	// prescription.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	prescription.QuantityValidator = prescriptionDescQuantity.Validators[0].(func(int) error)
	// prescriptionDescCreatedAt is the schema descriptor for created_at field.
	prescriptionDescCreatedAt := prescriptionFields[8].Descriptor()
	// prescription.DefaultCreatedAt holds the default value on creation for the created_at field.
	prescription.DefaultCreatedAt = prescriptionDescCreatedAt.Default.(func() time.Time)
	// prescriptionDescUpdatedAt is the schema descriptor for updated_at field.
	prescriptionDescUpdatedAt := prescriptionFields[9].Descriptor()
	// prescription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	prescription.DefaultUpdatedAt = prescriptionDescUpdatedAt.Default.(func() time.Time)
	// prescription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	prescription.UpdateDefaultUpdatedAt = prescriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// prescriptionDescID is the schema descriptor for id field.
	prescriptionDescID := prescriptionFields[0].Descriptor()
	// prescription.DefaultID holds the default value on creation for the id field.
	prescription.DefaultID = prescriptionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[3].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = userDescFirstName.Validators[0].(func(string) error)
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[4].Descriptor()
	// user.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	user.LastNameValidator = userDescLastName.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[11].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[12].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
