// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LoneWolfPR/MedMarket/backend/ent/predicate"
	"github.com/LoneWolfPR/MedMarket/backend/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *UserUpdate) SetFirstName(v string) *UserUpdate {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableFirstName(v *string) *UserUpdate {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *UserUpdate) SetLastName(v string) *UserUpdate {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastName(v *string) *UserUpdate {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *UserUpdate) SetPhone(v string) *UserUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePhone(v *string) *UserUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *UserUpdate) ClearPhone() *UserUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetAddressStreet1 sets the "address_street1" field.
func (_u *UserUpdate) SetAddressStreet1(v string) *UserUpdate {
	_u.mutation.SetAddressStreet1(v)
	return _u
}

// SetNillableAddressStreet1 sets the "address_street1" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAddressStreet1(v *string) *UserUpdate {
	if v != nil {
		_u.SetAddressStreet1(*v)
	}
	return _u
}

// ClearAddressStreet1 clears the value of the "address_street1" field.
func (_u *UserUpdate) ClearAddressStreet1() *UserUpdate {
	_u.mutation.ClearAddressStreet1()
	return _u
}

// SetAddressStreet2 sets the "address_street2" field.
func (_u *UserUpdate) SetAddressStreet2(v string) *UserUpdate {
	_u.mutation.SetAddressStreet2(v)
	return _u
}

// SetNillableAddressStreet2 sets the "address_street2" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAddressStreet2(v *string) *UserUpdate {
	if v != nil {
		_u.SetAddressStreet2(*v)
	}
	return _u
}

// ClearAddressStreet2 clears the value of the "address_street2" field.
func (_u *UserUpdate) ClearAddressStreet2() *UserUpdate {
	_u.mutation.ClearAddressStreet2()
	return _u
}

// SetAddressCity sets the "address_city" field.
func (_u *UserUpdate) SetAddressCity(v string) *UserUpdate {
	_u.mutation.SetAddressCity(v)
	return _u
}

// SetNillableAddressCity sets the "address_city" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAddressCity(v *string) *UserUpdate {
	if v != nil {
		_u.SetAddressCity(*v)
	}
	return _u
}

// ClearAddressCity clears the value of the "address_city" field.
func (_u *UserUpdate) ClearAddressCity() *UserUpdate {
	_u.mutation.ClearAddressCity()
	return _u
}

// SetAddressState sets the "address_state" field.
func (_u *UserUpdate) SetAddressState(v string) *UserUpdate {
	_u.mutation.SetAddressState(v)
	return _u
}

// SetNillableAddressState sets the "address_state" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAddressState(v *string) *UserUpdate {
	if v != nil {
		_u.SetAddressState(*v)
	}
	return _u
}

// ClearAddressState clears the value of the "address_state" field.
func (_u *UserUpdate) ClearAddressState() *UserUpdate {
	_u.mutation.ClearAddressState()
	return _u
}

// SetAddressZip sets the "address_zip" field.
func (_u *UserUpdate) SetAddressZip(v string) *UserUpdate {
	_u.mutation.SetAddressZip(v)
	return _u
}

// SetNillableAddressZip sets the "address_zip" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAddressZip(v *string) *UserUpdate {
	if v != nil {
		_u.SetAddressZip(*v)
	}
	return _u
}

// ClearAddressZip clears the value of the "address_zip" field.
func (_u *UserUpdate) ClearAddressZip() *UserUpdate {
	_u.mutation.ClearAddressZip()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirstName(); ok {
		if err := user.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "User.first_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastName(); ok {
		if err := user.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`ent: validator failed for field "User.last_name": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(user.FieldFirstName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(user.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(user.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.AddressStreet1(); ok {
		_spec.SetField(user.FieldAddressStreet1, field.TypeString, value)
	}
	if _u.mutation.AddressStreet1Cleared() {
		_spec.ClearField(user.FieldAddressStreet1, field.TypeString)
	}
	if value, ok := _u.mutation.AddressStreet2(); ok {
		_spec.SetField(user.FieldAddressStreet2, field.TypeString, value)
	}
	if _u.mutation.AddressStreet2Cleared() {
		_spec.ClearField(user.FieldAddressStreet2, field.TypeString)
	}
	if value, ok := _u.mutation.AddressCity(); ok {
		_spec.SetField(user.FieldAddressCity, field.TypeString, value)
	}
	if _u.mutation.AddressCityCleared() {
		_spec.ClearField(user.FieldAddressCity, field.TypeString)
	}
	if value, ok := _u.mutation.AddressState(); ok {
		_spec.SetField(user.FieldAddressState, field.TypeString, value)
	}
	if _u.mutation.AddressStateCleared() {
		_spec.ClearField(user.FieldAddressState, field.TypeString)
	}
	if value, ok := _u.mutation.AddressZip(); ok {
		_spec.SetField(user.FieldAddressZip, field.TypeString, value)
	}
	if _u.mutation.AddressZipCleared() {
		_spec.ClearField(user.FieldAddressZip, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *UserUpdateOne) SetFirstName(v string) *UserUpdateOne {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableFirstName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *UserUpdateOne) SetLastName(v string) *UserUpdateOne {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *UserUpdateOne) SetPhone(v string) *UserUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePhone(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *UserUpdateOne) ClearPhone() *UserUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetAddressStreet1 sets the "address_street1" field.
func (_u *UserUpdateOne) SetAddressStreet1(v string) *UserUpdateOne {
	_u.mutation.SetAddressStreet1(v)
	return _u
}

// SetNillableAddressStreet1 sets the "address_street1" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAddressStreet1(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAddressStreet1(*v)
	}
	return _u
}

// ClearAddressStreet1 clears the value of the "address_street1" field.
func (_u *UserUpdateOne) ClearAddressStreet1() *UserUpdateOne {
	_u.mutation.ClearAddressStreet1()
	return _u
}

// SetAddressStreet2 sets the "address_street2" field.
func (_u *UserUpdateOne) SetAddressStreet2(v string) *UserUpdateOne {
	_u.mutation.SetAddressStreet2(v)
	return _u
}

// SetNillableAddressStreet2 sets the "address_street2" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAddressStreet2(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAddressStreet2(*v)
	}
	return _u
}

// ClearAddressStreet2 clears the value of the "address_street2" field.
func (_u *UserUpdateOne) ClearAddressStreet2() *UserUpdateOne {
	_u.mutation.ClearAddressStreet2()
	return _u
}

// SetAddressCity sets the "address_city" field.
func (_u *UserUpdateOne) SetAddressCity(v string) *UserUpdateOne {
	_u.mutation.SetAddressCity(v)
	return _u
}

// SetNillableAddressCity sets the "address_city" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAddressCity(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAddressCity(*v)
	}
	return _u
}

// ClearAddressCity clears the value of the "address_city" field.
func (_u *UserUpdateOne) ClearAddressCity() *UserUpdateOne {
	_u.mutation.ClearAddressCity()
	return _u
}

// SetAddressState sets the "address_state" field.
func (_u *UserUpdateOne) SetAddressState(v string) *UserUpdateOne {
	_u.mutation.SetAddressState(v)
	return _u
}

// SetNillableAddressState sets the "address_state" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAddressState(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAddressState(*v)
	}
	return _u
}

// ClearAddressState clears the value of the "address_state" field.
func (_u *UserUpdateOne) ClearAddressState() *UserUpdateOne {
	_u.mutation.ClearAddressState()
	return _u
}

// SetAddressZip sets the "address_zip" field.
func (_u *UserUpdateOne) SetAddressZip(v string) *UserUpdateOne {
	_u.mutation.SetAddressZip(v)
	return _u
}

// SetNillableAddressZip sets the "address_zip" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAddressZip(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAddressZip(*v)
	}
	return _u
}

// ClearAddressZip clears the value of the "address_zip" field.
func (_u *UserUpdateOne) ClearAddressZip() *UserUpdateOne {
	_u.mutation.ClearAddressZip()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirstName(); ok {
		if err := user.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "User.first_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastName(); ok {
		if err := user.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`ent: validator failed for field "User.last_name": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(user.FieldFirstName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(user.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(user.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.AddressStreet1(); ok {
		_spec.SetField(user.FieldAddressStreet1, field.TypeString, value)
	}
	if _u.mutation.AddressStreet1Cleared() {
		_spec.ClearField(user.FieldAddressStreet1, field.TypeString)
	}
	if value, ok := _u.mutation.AddressStreet2(); ok {
		_spec.SetField(user.FieldAddressStreet2, field.TypeString, value)
	}
	if _u.mutation.AddressStreet2Cleared() {
		_spec.ClearField(user.FieldAddressStreet2, field.TypeString)
	}
	if value, ok := _u.mutation.AddressCity(); ok {
		_spec.SetField(user.FieldAddressCity, field.TypeString, value)
	}
	if _u.mutation.AddressCityCleared() {
		_spec.ClearField(user.FieldAddressCity, field.TypeString)
	}
	if value, ok := _u.mutation.AddressState(); ok {
		_spec.SetField(user.FieldAddressState, field.TypeString, value)
	}
	if _u.mutation.AddressStateCleared() {
		_spec.ClearField(user.FieldAddressState, field.TypeString)
	}
	if value, ok := _u.mutation.AddressZip(); ok {
		_spec.SetField(user.FieldAddressZip, field.TypeString, value)
	}
	if _u.mutation.AddressZipCleared() {
		_spec.ClearField(user.FieldAddressZip, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
