//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Address defines model for Address.
type Address struct {
	City string `json:"city"`

	// State Two-letter state abbreviation
	State   string  `json:"state"`
	Street1 string  `json:"street1"`
	Street2 *string `json:"street2,omitempty"`
	Zip     string  `json:"zip"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// OrderRequest defines model for OrderRequest.
type OrderRequest struct {
	// OfferId The offer to order, from a prior price search
	OfferId openapi_types.UUID `json:"offerId"`

	// PaymentMethod A payment method token (e.g. a Stripe pm_... token)
	PaymentMethod string `json:"paymentMethod"`
}

// OrderResponse defines model for OrderResponse.
type OrderResponse struct {
	ItemName string             `json:"itemName"`
	OrderId  openapi_types.UUID `json:"orderId"`
	Quantity int                `json:"quantity"`

	// Status The order's current lifecycle status
	Status string `json:"status"`
}

// PrescriptionResponse defines model for PrescriptionResponse.
type PrescriptionResponse struct {
	// DocumentUrl Short-lived presigned URL to the uploaded document
	DocumentUrl   string             `json:"documentUrl"`
	Id            openapi_types.UUID `json:"id"`
	MedName       string             `json:"medName"`
	PhysicianName string             `json:"physicianName"`
	Quantity      int                `json:"quantity"`
	StrengthUnit  string             `json:"strengthUnit"`
	StrengthValue string             `json:"strengthValue"`
}

// QuoteResponse defines model for QuoteResponse.
type QuoteResponse struct {
	// OfferId The offer this quote was persisted as. Orders reference it by id so the customer is charged the price that was quoted here, rather than whatever the pharmacy re-quotes at order time. Valid until the offer expires.
	OfferId    openapi_types.UUID `json:"offerId"`
	PharmacyId openapi_types.UUID `json:"pharmacyId"`

	// PharmacyItemId The pharmacy's own identifier for the item (SKU, code, ...)
	PharmacyItemId string `json:"pharmacyItemId"`
	PharmacyName   string `json:"pharmacyName"`

	// TotalCents Unit price multiplied by the prescription quantity, in cents
	TotalCents int64 `json:"totalCents"`

	// UnitPriceCents Price per unit, in cents
	UnitPriceCents int64 `json:"unitPriceCents"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Address   *Address            `json:"address,omitempty"`
	Email     openapi_types.Email `json:"email"`
	FirstName string              `json:"firstName"`
	LastName  string              `json:"lastName"`
	Password  string              `json:"password"`
	Phone     *string             `json:"phone,omitempty"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	Token string `json:"token"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Address   *Address            `json:"address,omitempty"`
	Email     openapi_types.Email `json:"email"`
	FirstName string              `json:"firstName"`
	Id        openapi_types.UUID  `json:"id"`
	LastName  string              `json:"lastName"`
	Phone     *string             `json:"phone,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Gone defines model for Gone.
type Gone = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// UploadPrescriptionMultipartBody defines parameters for UploadPrescription.
type UploadPrescriptionMultipartBody struct {
	// Document The prescription document (image or PDF)
	Document      openapi_types.File `json:"document"`
	MedName       string             `json:"medName"`
	PhysicianName string             `json:"physicianName"`
	Quantity      int                `json:"quantity"`
	StrengthUnit  string             `json:"strengthUnit"`
	StrengthValue string             `json:"strengthValue"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = OrderRequest

// UploadPrescriptionMultipartRequestBody defines body for UploadPrescription for multipart/form-data ContentType.
type UploadPrescriptionMultipartRequestBody UploadPrescriptionMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Exchange credentials for a bearer token
	// (POST /api/auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Get the authenticated user's profile
	// (GET /api/auth/profile)
	GetProfile(w http.ResponseWriter, r *http.Request)
	// Register a new user account
	// (POST /api/auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// Place an order for a persisted offer
	// (POST /api/orders)
	CreateOrder(w http.ResponseWriter, r *http.Request)
	// List the authenticated user's prescriptions
	// (GET /api/prescriptions)
	ListPrescriptions(w http.ResponseWriter, r *http.Request)
	// Upload a prescription document and its metadata
	// (POST /api/prescriptions/upload)
	UploadPrescription(w http.ResponseWriter, r *http.Request)
	// Search pharmacies for prices on a prescription's medication
	// (POST /api/prescriptions/{id}/search)
	SearchPrescriptionPrices(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrder(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPrescriptions operation middleware
func (siw *ServerInterfaceWrapper) ListPrescriptions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPrescriptions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadPrescription operation middleware
func (siw *ServerInterfaceWrapper) UploadPrescription(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadPrescription(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchPrescriptionPrices operation middleware
func (siw *ServerInterfaceWrapper) SearchPrescriptionPrices(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchPrescriptionPrices(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/auth/login", wrapper.LoginUser)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/auth/profile", wrapper.GetProfile)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/auth/register", wrapper.RegisterUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/orders", wrapper.CreateOrder)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/prescriptions", wrapper.ListPrescriptions)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/prescriptions/upload", wrapper.UploadPrescription)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/prescriptions/{id}/search", wrapper.SearchPrescriptionPrices)

	return m
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type GoneJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type LoginUserRequestObject struct {
	Body *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200JSONResponse TokenResponse

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfileRequestObject struct {
}

type GetProfileResponseObject interface {
	VisitGetProfileResponse(w http.ResponseWriter) error
}

type GetProfile200JSONResponse UserResponse

func (response GetProfile200JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetProfile401JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201JSONResponse UserResponse

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser409JSONResponse Error

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrderRequestObject struct {
	Body *CreateOrderJSONRequestBody
}

type CreateOrderResponseObject interface {
	VisitCreateOrderResponse(w http.ResponseWriter) error
}

type CreateOrder201JSONResponse OrderResponse

func (response CreateOrder201JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateOrder400JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateOrder401JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateOrder404JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder409JSONResponse struct{ ConflictJSONResponse }

func (response CreateOrder409JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder410JSONResponse struct{ GoneJSONResponse }

func (response CreateOrder410JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(410)
	_, err := buf.WriteTo(w)
	return err
}

type ListPrescriptionsRequestObject struct {
}

type ListPrescriptionsResponseObject interface {
	VisitListPrescriptionsResponse(w http.ResponseWriter) error
}

type ListPrescriptions200JSONResponse []PrescriptionResponse

func (response ListPrescriptions200JSONResponse) VisitListPrescriptionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPrescriptions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListPrescriptions401JSONResponse) VisitListPrescriptionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UploadPrescriptionRequestObject struct {
	Body *multipart.Reader
}

type UploadPrescriptionResponseObject interface {
	VisitUploadPrescriptionResponse(w http.ResponseWriter) error
}

type UploadPrescription201JSONResponse PrescriptionResponse

func (response UploadPrescription201JSONResponse) VisitUploadPrescriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type UploadPrescription400JSONResponse struct{ BadRequestJSONResponse }

func (response UploadPrescription400JSONResponse) VisitUploadPrescriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UploadPrescription401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UploadPrescription401JSONResponse) VisitUploadPrescriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SearchPrescriptionPricesRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type SearchPrescriptionPricesResponseObject interface {
	VisitSearchPrescriptionPricesResponse(w http.ResponseWriter) error
}

type SearchPrescriptionPrices200JSONResponse []QuoteResponse

func (response SearchPrescriptionPrices200JSONResponse) VisitSearchPrescriptionPricesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchPrescriptionPrices401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SearchPrescriptionPrices401JSONResponse) VisitSearchPrescriptionPricesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SearchPrescriptionPrices404JSONResponse struct{ NotFoundJSONResponse }

func (response SearchPrescriptionPrices404JSONResponse) VisitSearchPrescriptionPricesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Exchange credentials for a bearer token
	// (POST /api/auth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// Get the authenticated user's profile
	// (GET /api/auth/profile)
	GetProfile(ctx context.Context, request GetProfileRequestObject) (GetProfileResponseObject, error)
	// Register a new user account
	// (POST /api/auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// Place an order for a persisted offer
	// (POST /api/orders)
	CreateOrder(ctx context.Context, request CreateOrderRequestObject) (CreateOrderResponseObject, error)
	// List the authenticated user's prescriptions
	// (GET /api/prescriptions)
	ListPrescriptions(ctx context.Context, request ListPrescriptionsRequestObject) (ListPrescriptionsResponseObject, error)
	// Upload a prescription document and its metadata
	// (POST /api/prescriptions/upload)
	UploadPrescription(ctx context.Context, request UploadPrescriptionRequestObject) (UploadPrescriptionResponseObject, error)
	// Search pharmacies for prices on a prescription's medication
	// (POST /api/prescriptions/{id}/search)
	SearchPrescriptionPrices(ctx context.Context, request SearchPrescriptionPricesRequestObject) (SearchPrescriptionPricesResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(w http.ResponseWriter, r *http.Request) {
	var request LoginUserRequestObject

	var body LoginUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProfile operation middleware
func (sh *strictHandler) GetProfile(w http.ResponseWriter, r *http.Request) {
	var request GetProfileRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProfile(ctx, request.(GetProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProfile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProfileResponseObject); ok {
		if err := validResponse.VisitGetProfileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(w http.ResponseWriter, r *http.Request) {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx, request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		if err := validResponse.VisitRegisterUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrder operation middleware
func (sh *strictHandler) CreateOrder(w http.ResponseWriter, r *http.Request) {
	var request CreateOrderRequestObject

	var body CreateOrderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrder(ctx, request.(CreateOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrderResponseObject); ok {
		if err := validResponse.VisitCreateOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPrescriptions operation middleware
func (sh *strictHandler) ListPrescriptions(w http.ResponseWriter, r *http.Request) {
	var request ListPrescriptionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPrescriptions(ctx, request.(ListPrescriptionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPrescriptions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPrescriptionsResponseObject); ok {
		if err := validResponse.VisitListPrescriptionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadPrescription operation middleware
func (sh *strictHandler) UploadPrescription(w http.ResponseWriter, r *http.Request) {
	var request UploadPrescriptionRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadPrescription(ctx, request.(UploadPrescriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadPrescription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadPrescriptionResponseObject); ok {
		if err := validResponse.VisitUploadPrescriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchPrescriptionPrices operation middleware
func (sh *strictHandler) SearchPrescriptionPrices(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request SearchPrescriptionPricesRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchPrescriptionPrices(ctx, request.(SearchPrescriptionPricesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchPrescriptionPrices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchPrescriptionPricesResponseObject); ok {
		if err := validResponse.VisitSearchPrescriptionPricesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Flfb9vIEf8qg22BJAAj2bmgQPWWS5MgbXL1xfH1ITCKNTkS90LuMrNDO7pA372YXVIkLVKSm7MP95KI",
	"+2dm9jf/x99U6srKWbTs1eKbIvSVsx7Dx486+4BfavQsX6mzjDb81FVVmFSzcXb+q3dW1nyaY6nl118J",
	"l2qh/jLvSM/jrp+/InKkNptNojL0KZlKiKiFemuvdWEyoIbhJlEvnV0WJn0A5h9zbBlD2nD1cGM4B84R",
	"0poILYNnzQhuGRYJvaspRZH0jbP4oFJituUPxoN1UDi7QgJ9rU2hr4og1k+OX7vaZn+YaJlDEY4Bv5qo",
	"0wura84dmd/wAcR6b7w3dgWOwDT2lRJmaNnowiu50NAQFi+yjNCHnxW5ColN9IPU8Fr+53WFaqE8k7Er",
	"eU0wCNm5hcaNe1ogM1JjMvrqivDahLepRJX66zu0K87V4lmiSmN7XyM8CJFPJ/jL3rPRvd9MNbK+SZTo",
	"yZDA/2lLPIlvbF8Ub19upXFXv2Ia9Beh3kGoRO/1Cg8zbA+O0X7nVsb2As6QBZbaFPJj6ajUrBbNyghk",
	"lfb+xlE2OL1dTA6I2JLdXhiT9d+UIU3K6pZLpLfZiGXkEj+WSMAOnNBIYEmuBA0VGUfyb4rgUVOaq6ST",
	"vq5NNv7UdYmW3yPnboTfC2gOQBlOALvPaOExzlYz0HDOZCqEqvzvbDaLe08O4tM+7jbzPTDFnLKLk2Es",
	"f9IljhpwgOftUIlTMHypteWhlxrLuEJq3bT2E9oQLo/8NsYXZonpOi0QmlsH4WjETLrX9OTZMh9D54w6",
	"caZBylxaC8wXVOw+4Tx3xE8Lc40ZVITerCxmcPHhnRiYpKm6KpzOMIOWzBh85jiUS8wmtVXla29So+3k",
	"iUM6ohAEL6zhyVgnB37RRX1EoAkvGArVPeA2tVvsB/rrwz+mxJ9rxzitvWNCQW48fBEycKM9VEjehDyq",
	"/QyCB3kgXCKhlXTPcLUGk4F3TXHi2ZVIUgekuaYVZmE9RhLONQeqgX4GORImQJrzwFhbuMk143X4Qqhy",
	"TaVO10D4NNzwoDn6CLApcQa/hCxaWzZFuBGfgF8rQ+hnR4WshseRrr09zlhO4dieeeTB3VgwIcMvDRIs",
	"XXyY+CY8Pv/XRQKpyzCB2Wz2ZB+7STNmx7p42dbLQ1nEehrgy7pgUxUGM1FXVEh3FloDS8BYSAO1HnTG",
	"8t+ed9L13KS2hs+EwYQEYU9MCOTk3ahPx/lOY7cA2lHPjoQDwMb85wOuxNqnk6nuyrJ9RWBbvW2Su5QK",
	"S0OeJ3Vd6D2bd6wyBKqmTdgfuTqRegIkx5UlHyWFTwejkOEPSxCPjdG/8PvS+R+oqSMz2H6FHqefQLkV",
	"c1RZu8hJ/sK0JsPrc0Eh4nWFmpBe1FL6t1+v2yf88z8fVdOeCKW4270pZ65iy2Ps0o0Fgl60iSFJVKHJ",
	"eFkoNAtY8OLsrQRtNlwI1feYvdf0GVk2VKKuJRcFeiez09lJKMsqtLoyaqF+mJ3MfggWyXl4z1xXZi79",
	"3byQUj4YiIsuLWYS2h8J4bHSF1tSEVr0/KPL1r9bQzjoJDZDBTLVGBZ6g45nJye/G++hC440paJvyU+p",
	"ZswE0ecnp1NEt1LOB41zsKe6LDWt1UK9+prm2q6w39uGxKchWk2s7EXNeuXFhIWUuhQqncoqcktTBPtf",
	"4YjO3iCfNUfuEb1BgJkYNNQepVGKsvz/+DX+qBafhp746XJz2Yf3DXLI37qvtyDEI78VYz+21OS4aY9o",
	"s+A9OsXtRHuUX5w+mGZlXyy484qTw1rtTSjDlb/f/0zplUR+0AWhzqROjqDuOGWLNmiweBNtVqepq2MH",
	"Nm4sodD201byMsATWoJ7MpLBXOOBLWQ4LBiBPhyQ3JV+h4ncOVbIpeeHL22HrZ0h7r+wHW/LhdMjXhKm",
	"zHcKXWcCFWjbdHAxJ3T9Zajwe9bYmF9nj/2WxU9mhnfG89ng5HcmCGnWDlaRo8OTzbY+0kR6vS+DhODd",
	"F/r+M4kAtS+VDCFstTJcn1DOPM55pkPHRdjvg7Y3gsT2VRPPpUx8mmnWQx2Nz6gm2vN+Ldoehcem1CsE",
	"R3D2j9dP+g3qlbEC2J98AtUbuH3/HGqkpXjQ2DzubbveNWg7vjeb36szRocIg/cx69Q2A8MeSmQdrP+u",
	"DvnNZJt5M8if9MrzsN8HLYxOfOiqSJfIoR74dNCr2MUmT0k/GOYQnKtE2eAKsWUdGkvSU/yBtllwu/94",
	"PpyjHhHIf47zyfDnk97s0qCPU0/PLv0cdkrMGuESSHPUFXqG0Lk/VElwF8OMNtF/zrL9w5AHZ29Z7CPf",
	"e94+Iw0i0HVrTzUVaqHmanO5+V8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
