// Code generated by ent, DO NOT EDIT.

package prescription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the prescription type in the database.
	Label = "prescription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldDocumentKey holds the string denoting the document_key field in the database.
	FieldDocumentKey = "document_key"
	// FieldPhysicianName holds the string denoting the physician_name field in the database.
	FieldPhysicianName = "physician_name"
	// FieldMedName holds the string denoting the med_name field in the database.
	FieldMedName = "med_name"
	// FieldMedStrengthValue holds the string denoting the med_strength_value field in the database.
	FieldMedStrengthValue = "med_strength_value"
	// FieldMedStrengthUnit holds the string denoting the med_strength_unit field in the database.
	FieldMedStrengthUnit = "med_strength_unit"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeOffers holds the string denoting the offers edge name in mutations.
	EdgeOffers = "offers"
	// Table holds the table name of the prescription in the database.
	Table = "prescriptions"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "prescriptions"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_id"
	// OffersTable is the table that holds the offers relation/edge.
	OffersTable = "offers"
	// OffersInverseTable is the table name for the Offer entity.
	// It exists in this package in order to avoid circular dependency with the "offer" package.
	OffersInverseTable = "offers"
	// OffersColumn is the table column denoting the offers relation/edge.
	OffersColumn = "prescription_id"
)

// Columns holds all SQL columns for prescription fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldDocumentKey,
	FieldPhysicianName,
	FieldMedName,
	FieldMedStrengthValue,
	FieldMedStrengthUnit,
	FieldQuantity,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DocumentKeyValidator is a validator for the "document_key" field. It is called by the builders before save.
	DocumentKeyValidator func(string) error
	// PhysicianNameValidator is a validator for the "physician_name" field. It is called by the builders before save.
	PhysicianNameValidator func(string) error
	// MedNameValidator is a validator for the "med_name" field. It is called by the builders before save.
	MedNameValidator func(string) error
	// MedStrengthValueValidator is a validator for the "med_strength_value" field. It is called by the builders before save.
	MedStrengthValueValidator func(string) error
	// MedStrengthUnitValidator is a validator for the "med_strength_unit" field. It is called by the builders before save.
	MedStrengthUnitValidator func(string) error
	// QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	QuantityValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Prescription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByDocumentKey orders the results by the document_key field.
func ByDocumentKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentKey, opts...).ToFunc()
}

// ByPhysicianName orders the results by the physician_name field.
func ByPhysicianName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhysicianName, opts...).ToFunc()
}

// ByMedName orders the results by the med_name field.
func ByMedName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMedName, opts...).ToFunc()
}

// ByMedStrengthValue orders the results by the med_strength_value field.
func ByMedStrengthValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMedStrengthValue, opts...).ToFunc()
}

// ByMedStrengthUnit orders the results by the med_strength_unit field.
func ByMedStrengthUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMedStrengthUnit, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByOffersCount orders the results by offers count.
func ByOffersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOffersStep(), opts...)
	}
}

// ByOffers orders the results by offers terms.
func ByOffers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOffersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
func newOffersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OffersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OffersTable, OffersColumn),
	)
}
