// Code generated by ent, DO NOT EDIT.

package prescription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the prescription type in the database.
	Label = "prescription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldDocumentKey holds the string denoting the document_key field in the database.
	FieldDocumentKey = "document_key"
	// FieldPhysicianName holds the string denoting the physician_name field in the database.
	FieldPhysicianName = "physician_name"
	// FieldMedName holds the string denoting the med_name field in the database.
	FieldMedName = "med_name"
	// FieldMedStrengthValue holds the string denoting the med_strength_value field in the database.
	FieldMedStrengthValue = "med_strength_value"
	// FieldMedStrengthUnit holds the string denoting the med_strength_unit field in the database.
	FieldMedStrengthUnit = "med_strength_unit"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the prescription in the database.
	Table = "prescriptions"
)

// Columns holds all SQL columns for prescription fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldDocumentKey,
	FieldPhysicianName,
	FieldMedName,
	FieldMedStrengthValue,
	FieldMedStrengthUnit,
	FieldQuantity,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DocumentKeyValidator is a validator for the "document_key" field. It is called by the builders before save.
	DocumentKeyValidator func(string) error
	// PhysicianNameValidator is a validator for the "physician_name" field. It is called by the builders before save.
	PhysicianNameValidator func(string) error
	// MedNameValidator is a validator for the "med_name" field. It is called by the builders before save.
	MedNameValidator func(string) error
	// MedStrengthValueValidator is a validator for the "med_strength_value" field. It is called by the builders before save.
	MedStrengthValueValidator func(string) error
	// MedStrengthUnitValidator is a validator for the "med_strength_unit" field. It is called by the builders before save.
	MedStrengthUnitValidator func(string) error
	// QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	QuantityValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Prescription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByDocumentKey orders the results by the document_key field.
func ByDocumentKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentKey, opts...).ToFunc()
}

// ByPhysicianName orders the results by the physician_name field.
func ByPhysicianName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhysicianName, opts...).ToFunc()
}

// ByMedName orders the results by the med_name field.
func ByMedName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMedName, opts...).ToFunc()
}

// ByMedStrengthValue orders the results by the med_strength_value field.
func ByMedStrengthValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMedStrengthValue, opts...).ToFunc()
}

// ByMedStrengthUnit orders the results by the med_strength_unit field.
func ByMedStrengthUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMedStrengthUnit, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
