// Code generated by ent, DO NOT EDIT.

package prescription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/LoneWolfPR/MedMarket/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldUserID, v))
}

// DocumentKey applies equality check predicate on the "document_key" field. It's identical to DocumentKeyEQ.
func DocumentKey(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldDocumentKey, v))
}

// PhysicianName applies equality check predicate on the "physician_name" field. It's identical to PhysicianNameEQ.
func PhysicianName(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldPhysicianName, v))
}

// MedName applies equality check predicate on the "med_name" field. It's identical to MedNameEQ.
func MedName(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldMedName, v))
}

// MedStrengthValue applies equality check predicate on the "med_strength_value" field. It's identical to MedStrengthValueEQ.
func MedStrengthValue(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldMedStrengthValue, v))
}

// MedStrengthUnit applies equality check predicate on the "med_strength_unit" field. It's identical to MedStrengthUnitEQ.
func MedStrengthUnit(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldMedStrengthUnit, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldQuantity, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.Prescription {
	return predicate.Prescription(sql.FieldLTE(FieldUserID, v))
}

// DocumentKeyEQ applies the EQ predicate on the "document_key" field.
func DocumentKeyEQ(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldDocumentKey, v))
}

// DocumentKeyNEQ applies the NEQ predicate on the "document_key" field.
func DocumentKeyNEQ(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldNEQ(FieldDocumentKey, v))
}

// DocumentKeyIn applies the In predicate on the "document_key" field.
func DocumentKeyIn(vs ...string) predicate.Prescription {
	return predicate.Prescription(sql.FieldIn(FieldDocumentKey, vs...))
}

// DocumentKeyNotIn applies the NotIn predicate on the "document_key" field.
func DocumentKeyNotIn(vs ...string) predicate.Prescription {
	return predicate.Prescription(sql.FieldNotIn(FieldDocumentKey, vs...))
}

// DocumentKeyGT applies the GT predicate on the "document_key" field.
func DocumentKeyGT(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldGT(FieldDocumentKey, v))
}

// DocumentKeyGTE applies the GTE predicate on the "document_key" field.
func DocumentKeyGTE(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldGTE(FieldDocumentKey, v))
}

// DocumentKeyLT applies the LT predicate on the "document_key" field.
func DocumentKeyLT(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldLT(FieldDocumentKey, v))
}

// DocumentKeyLTE applies the LTE predicate on the "document_key" field.
func DocumentKeyLTE(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldLTE(FieldDocumentKey, v))
}

// DocumentKeyContains applies the Contains predicate on the "document_key" field.
func DocumentKeyContains(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldContains(FieldDocumentKey, v))
}

// DocumentKeyHasPrefix applies the HasPrefix predicate on the "document_key" field.
func DocumentKeyHasPrefix(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldHasPrefix(FieldDocumentKey, v))
}

// DocumentKeyHasSuffix applies the HasSuffix predicate on the "document_key" field.
func DocumentKeyHasSuffix(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldHasSuffix(FieldDocumentKey, v))
}

// DocumentKeyEqualFold applies the EqualFold predicate on the "document_key" field.
func DocumentKeyEqualFold(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEqualFold(FieldDocumentKey, v))
}

// DocumentKeyContainsFold applies the ContainsFold predicate on the "document_key" field.
func DocumentKeyContainsFold(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldContainsFold(FieldDocumentKey, v))
}

// PhysicianNameEQ applies the EQ predicate on the "physician_name" field.
func PhysicianNameEQ(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldPhysicianName, v))
}

// PhysicianNameNEQ applies the NEQ predicate on the "physician_name" field.
func PhysicianNameNEQ(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldNEQ(FieldPhysicianName, v))
}

// PhysicianNameIn applies the In predicate on the "physician_name" field.
func PhysicianNameIn(vs ...string) predicate.Prescription {
	return predicate.Prescription(sql.FieldIn(FieldPhysicianName, vs...))
}

// PhysicianNameNotIn applies the NotIn predicate on the "physician_name" field.
func PhysicianNameNotIn(vs ...string) predicate.Prescription {
	return predicate.Prescription(sql.FieldNotIn(FieldPhysicianName, vs...))
}

// PhysicianNameGT applies the GT predicate on the "physician_name" field.
func PhysicianNameGT(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldGT(FieldPhysicianName, v))
}

// PhysicianNameGTE applies the GTE predicate on the "physician_name" field.
func PhysicianNameGTE(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldGTE(FieldPhysicianName, v))
}

// PhysicianNameLT applies the LT predicate on the "physician_name" field.
func PhysicianNameLT(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldLT(FieldPhysicianName, v))
}

// PhysicianNameLTE applies the LTE predicate on the "physician_name" field.
func PhysicianNameLTE(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldLTE(FieldPhysicianName, v))
}

// PhysicianNameContains applies the Contains predicate on the "physician_name" field.
func PhysicianNameContains(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldContains(FieldPhysicianName, v))
}

// PhysicianNameHasPrefix applies the HasPrefix predicate on the "physician_name" field.
func PhysicianNameHasPrefix(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldHasPrefix(FieldPhysicianName, v))
}

// PhysicianNameHasSuffix applies the HasSuffix predicate on the "physician_name" field.
func PhysicianNameHasSuffix(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldHasSuffix(FieldPhysicianName, v))
}

// PhysicianNameEqualFold applies the EqualFold predicate on the "physician_name" field.
func PhysicianNameEqualFold(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEqualFold(FieldPhysicianName, v))
}

// PhysicianNameContainsFold applies the ContainsFold predicate on the "physician_name" field.
func PhysicianNameContainsFold(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldContainsFold(FieldPhysicianName, v))
}

// MedNameEQ applies the EQ predicate on the "med_name" field.
func MedNameEQ(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldMedName, v))
}

// MedNameNEQ applies the NEQ predicate on the "med_name" field.
func MedNameNEQ(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldNEQ(FieldMedName, v))
}

// MedNameIn applies the In predicate on the "med_name" field.
func MedNameIn(vs ...string) predicate.Prescription {
	return predicate.Prescription(sql.FieldIn(FieldMedName, vs...))
}

// MedNameNotIn applies the NotIn predicate on the "med_name" field.
func MedNameNotIn(vs ...string) predicate.Prescription {
	return predicate.Prescription(sql.FieldNotIn(FieldMedName, vs...))
}

// MedNameGT applies the GT predicate on the "med_name" field.
func MedNameGT(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldGT(FieldMedName, v))
}

// MedNameGTE applies the GTE predicate on the "med_name" field.
func MedNameGTE(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldGTE(FieldMedName, v))
}

// MedNameLT applies the LT predicate on the "med_name" field.
func MedNameLT(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldLT(FieldMedName, v))
}

// MedNameLTE applies the LTE predicate on the "med_name" field.
func MedNameLTE(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldLTE(FieldMedName, v))
}

// MedNameContains applies the Contains predicate on the "med_name" field.
func MedNameContains(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldContains(FieldMedName, v))
}

// MedNameHasPrefix applies the HasPrefix predicate on the "med_name" field.
func MedNameHasPrefix(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldHasPrefix(FieldMedName, v))
}

// MedNameHasSuffix applies the HasSuffix predicate on the "med_name" field.
func MedNameHasSuffix(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldHasSuffix(FieldMedName, v))
}

// MedNameEqualFold applies the EqualFold predicate on the "med_name" field.
func MedNameEqualFold(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEqualFold(FieldMedName, v))
}

// MedNameContainsFold applies the ContainsFold predicate on the "med_name" field.
func MedNameContainsFold(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldContainsFold(FieldMedName, v))
}

// MedStrengthValueEQ applies the EQ predicate on the "med_strength_value" field.
func MedStrengthValueEQ(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldMedStrengthValue, v))
}

// MedStrengthValueNEQ applies the NEQ predicate on the "med_strength_value" field.
func MedStrengthValueNEQ(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldNEQ(FieldMedStrengthValue, v))
}

// MedStrengthValueIn applies the In predicate on the "med_strength_value" field.
func MedStrengthValueIn(vs ...string) predicate.Prescription {
	return predicate.Prescription(sql.FieldIn(FieldMedStrengthValue, vs...))
}

// MedStrengthValueNotIn applies the NotIn predicate on the "med_strength_value" field.
func MedStrengthValueNotIn(vs ...string) predicate.Prescription {
	return predicate.Prescription(sql.FieldNotIn(FieldMedStrengthValue, vs...))
}

// MedStrengthValueGT applies the GT predicate on the "med_strength_value" field.
func MedStrengthValueGT(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldGT(FieldMedStrengthValue, v))
}

// MedStrengthValueGTE applies the GTE predicate on the "med_strength_value" field.
func MedStrengthValueGTE(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldGTE(FieldMedStrengthValue, v))
}

// MedStrengthValueLT applies the LT predicate on the "med_strength_value" field.
func MedStrengthValueLT(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldLT(FieldMedStrengthValue, v))
}

// MedStrengthValueLTE applies the LTE predicate on the "med_strength_value" field.
func MedStrengthValueLTE(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldLTE(FieldMedStrengthValue, v))
}

// MedStrengthValueContains applies the Contains predicate on the "med_strength_value" field.
func MedStrengthValueContains(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldContains(FieldMedStrengthValue, v))
}

// MedStrengthValueHasPrefix applies the HasPrefix predicate on the "med_strength_value" field.
func MedStrengthValueHasPrefix(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldHasPrefix(FieldMedStrengthValue, v))
}

// MedStrengthValueHasSuffix applies the HasSuffix predicate on the "med_strength_value" field.
func MedStrengthValueHasSuffix(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldHasSuffix(FieldMedStrengthValue, v))
}

// MedStrengthValueEqualFold applies the EqualFold predicate on the "med_strength_value" field.
func MedStrengthValueEqualFold(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEqualFold(FieldMedStrengthValue, v))
}

// MedStrengthValueContainsFold applies the ContainsFold predicate on the "med_strength_value" field.
func MedStrengthValueContainsFold(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldContainsFold(FieldMedStrengthValue, v))
}

// MedStrengthUnitEQ applies the EQ predicate on the "med_strength_unit" field.
func MedStrengthUnitEQ(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldMedStrengthUnit, v))
}

// MedStrengthUnitNEQ applies the NEQ predicate on the "med_strength_unit" field.
func MedStrengthUnitNEQ(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldNEQ(FieldMedStrengthUnit, v))
}

// MedStrengthUnitIn applies the In predicate on the "med_strength_unit" field.
func MedStrengthUnitIn(vs ...string) predicate.Prescription {
	return predicate.Prescription(sql.FieldIn(FieldMedStrengthUnit, vs...))
}

// MedStrengthUnitNotIn applies the NotIn predicate on the "med_strength_unit" field.
func MedStrengthUnitNotIn(vs ...string) predicate.Prescription {
	return predicate.Prescription(sql.FieldNotIn(FieldMedStrengthUnit, vs...))
}

// MedStrengthUnitGT applies the GT predicate on the "med_strength_unit" field.
func MedStrengthUnitGT(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldGT(FieldMedStrengthUnit, v))
}

// MedStrengthUnitGTE applies the GTE predicate on the "med_strength_unit" field.
func MedStrengthUnitGTE(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldGTE(FieldMedStrengthUnit, v))
}

// MedStrengthUnitLT applies the LT predicate on the "med_strength_unit" field.
func MedStrengthUnitLT(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldLT(FieldMedStrengthUnit, v))
}

// MedStrengthUnitLTE applies the LTE predicate on the "med_strength_unit" field.
func MedStrengthUnitLTE(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldLTE(FieldMedStrengthUnit, v))
}

// MedStrengthUnitContains applies the Contains predicate on the "med_strength_unit" field.
func MedStrengthUnitContains(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldContains(FieldMedStrengthUnit, v))
}

// MedStrengthUnitHasPrefix applies the HasPrefix predicate on the "med_strength_unit" field.
func MedStrengthUnitHasPrefix(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldHasPrefix(FieldMedStrengthUnit, v))
}

// MedStrengthUnitHasSuffix applies the HasSuffix predicate on the "med_strength_unit" field.
func MedStrengthUnitHasSuffix(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldHasSuffix(FieldMedStrengthUnit, v))
}

// MedStrengthUnitEqualFold applies the EqualFold predicate on the "med_strength_unit" field.
func MedStrengthUnitEqualFold(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldEqualFold(FieldMedStrengthUnit, v))
}

// MedStrengthUnitContainsFold applies the ContainsFold predicate on the "med_strength_unit" field.
func MedStrengthUnitContainsFold(v string) predicate.Prescription {
	return predicate.Prescription(sql.FieldContainsFold(FieldMedStrengthUnit, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.Prescription {
	return predicate.Prescription(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.Prescription {
	return predicate.Prescription(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.Prescription {
	return predicate.Prescription(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.Prescription {
	return predicate.Prescription(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.Prescription {
	return predicate.Prescription(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.Prescription {
	return predicate.Prescription(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.Prescription {
	return predicate.Prescription(sql.FieldLTE(FieldQuantity, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Prescription {
	return predicate.Prescription(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Prescription) predicate.Prescription {
	return predicate.Prescription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Prescription) predicate.Prescription {
	return predicate.Prescription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Prescription) predicate.Prescription {
	return predicate.Prescription(sql.NotPredicates(p))
}
